* vars.h
* variable declarations
* generated by FormCalc 25 Oct 2014 23:21

#include "decl.h"

	double precision S, T, U
	common /kinvars/ S, T, U

	integer Hel(4)
	common /kinvars/ Hel

	double complex F3, F6, F35, F37, F49, F38, F40, F41, F110
	double complex F120, F121, F111, F122, F123, F36, F39, Pair4
	double complex Pair8, Pair11, Pair9, Pair10, Eps12, Eps13
	double complex Abb14, Abb15, Abb84, Abb85, Abb86, Abb87, Abb22
	double complex Abb23, Abb124, Abb125, Abb42, Abb50, Abb126
	double complex Abb127, Abb43, Abb51, Abb16, Abb61, Abb62
	double complex Abb24, Abb5, Abb44, Abb52, Abb7, Abb136, Abb137
	double complex Abb53, Abb45, Abb17, Abb63, Abb64, Abb25
	double complex Abb155, Abb156, Abb46, Abb47, Abb18, Abb65
	double complex Abb66, Abb26, Abb19, Abb67, Abb68, Abb27
	double complex AbbSum379, AbbSum381, AbbSum968, AbbSum716
	double complex AbbSum949, AbbSum801, AbbSum1099, AbbSum802
	double complex AbbSum969, AbbSum717, AbbSum950, AbbSum872
	double complex AbbSum578, AbbSum925, AbbSum939, AbbSum920
	double complex AbbSum923, AbbSum935, AbbSum361, AbbSum385
	double complex AbbSum220, AbbSum340, AbbSum202, AbbSum348
	double complex AbbSum344, AbbSum354, AbbSum417, AbbSum350
	double complex AbbSum208, AbbSum933, AbbSum929, AbbSum430
	double complex AbbSum400, AbbSum397, AbbSum421, AbbSum382
	double complex AbbSum766, AbbSum744, AbbSum746, AbbSum953
	double complex AbbSum885, AbbSum614, AbbSum612, AbbSum620
	double complex AbbSum616, AbbSum391, AbbSum718, AbbSum740
	double complex AbbSum728, AbbSum597, AbbSum760, AbbSum951
	double complex AbbSum736, AbbSum714, AbbSum738, AbbSum722
	double complex AbbSum602, AbbSum890, AbbSum245, AbbSum241
	double complex AbbSum250, AbbSum248, AbbSum976, AbbSum366
	double complex AbbSum958, AbbSum970, AbbSum972, AbbSum964
	double complex AbbSum358, AbbSum1112, AbbSum1073, AbbSum1087
	double complex AbbSum941, AbbSum408, AbbSum472, AbbSum635
	double complex AbbSum758, AbbSum764, AbbSum730, AbbSum30
	double complex AbbSum726, AbbSum20, AbbSum21, AbbSum752
	double complex AbbSum945, AbbSum414, AbbSum427, AbbSum76
	double complex AbbSum284, AbbSum222, AbbSum179, AbbSum911
	double complex AbbSum660, AbbSum224, AbbSum200, AbbSum664
	double complex AbbSum686, AbbSum1064, AbbSum562, AbbSum868
	double complex AbbSum986, AbbSum927, AbbSum940, AbbSum922
	double complex AbbSum924, AbbSum937, AbbSum209, AbbSum892
	double complex AbbSum1063, AbbSum921, AbbSum1057, AbbSum1065
	double complex AbbSum506, AbbSum309, AbbSum174, AbbSum484
	double complex AbbSum300, AbbSum334, AbbSum262, AbbSum1149
	double complex AbbSum180, AbbSum912, AbbSum152, AbbSum1016
	double complex AbbSum223, AbbSum236, AbbSum277, AbbSum285
	double complex AbbSum173, AbbSum485, AbbSum505, AbbSum1032
	double complex AbbSum452, AbbSum554, AbbSum320, AbbSum227
	double complex AbbSum289, AbbSum363, AbbSum388, AbbSum212
	double complex AbbSum230, AbbSum1004, AbbSum221, AbbSum231
	double complex AbbSum219, AbbSum342, AbbSum207, AbbSum349
	double complex AbbSum347, AbbSum175, AbbSum128, AbbSum513
	double complex AbbSum138, AbbSum355, AbbSum420, AbbSum353
	double complex AbbSum211, AbbSum934, AbbSum932, AbbSum560
	double complex AbbSum203, AbbSum288, AbbSum226, AbbSum321
	double complex AbbSum1031, AbbSum563, AbbSum1133, AbbSum687
	double complex AbbSum1050, AbbSum1054, AbbSum841, AbbSum916
	double complex AbbSum631, AbbSum1102, AbbSum593, AbbSum665
	double complex AbbSum919, AbbSum433, AbbSum403, AbbSum399
	double complex AbbSum538, AbbSum815, AbbSum914, AbbSum887
	double complex AbbSum626, AbbSum641, AbbSum905, AbbSum915
	double complex AbbSum588, AbbSum589, AbbSum879, AbbSum586
	double complex AbbSum680, AbbSum622, AbbSum653, AbbSum624
	double complex AbbSum907, AbbSum661, AbbSum166, AbbSum232
	double complex AbbSum225, AbbSum239, AbbSum201, AbbSum191
	double complex AbbSum195, AbbSum674, AbbSum703, AbbSum690
	double complex AbbSum424, AbbSum384, AbbSum814, AbbSum917
	double complex AbbSum918, AbbSum1103, AbbSum795, AbbSum767
	double complex AbbSum745, AbbSum747, AbbSum1053, AbbSum1049
	double complex AbbSum1138, AbbSum1134, AbbSum783, AbbSum859
	double complex AbbSum546, AbbSum956, AbbSum886, AbbSum606
	double complex AbbSum884, AbbSum615, AbbSum613, AbbSum611
	double complex AbbSum913, AbbSum1047, AbbSum621, AbbSum618
	double complex AbbSum394, AbbSum719, AbbSum741, AbbSum729
	double complex AbbSum601, AbbSum761, AbbSum952, AbbSum737
	double complex AbbSum715, AbbSum739, AbbSum590, AbbSum569
	double complex AbbSum820, AbbSum723, AbbSum605, AbbSum866
	double complex AbbSum598, AbbSum1119, AbbSum1040, AbbSum237
	double complex AbbSum197, AbbSum853, AbbSum869, AbbSum477
	double complex AbbSum539, AbbSum824, AbbSum796, AbbSum517
	double complex AbbSum704, AbbSum691, AbbSum1020, AbbSum1139
	double complex AbbSum803, AbbSum833, AbbSum488, AbbSum529
	double complex AbbSum263, AbbSum888, AbbSum240, AbbSum1078
	double complex AbbSum880, AbbSum1150, AbbSum238, AbbSum278
	double complex AbbSum906, AbbSum898, AbbSum196, AbbSum192
	double complex AbbSum587, AbbSum900, AbbSum908, AbbSum895
	double complex AbbSum70, AbbSum181, AbbSum157, AbbSum627
	double complex AbbSum625, AbbSum642, AbbSum654, AbbSum623
	double complex AbbSum675, AbbSum681, AbbSum489, AbbSum530
	double complex AbbSum832, AbbSum804, AbbSum335, AbbSum1019
	double complex AbbSum233, AbbSum594, AbbSum167, AbbSum825
	double complex AbbSum518, AbbSum632, AbbSum301, AbbSum1116
	double complex AbbSum310, AbbSum1157, AbbSum1093, AbbSum891
	double complex AbbSum251, AbbSum889, AbbSum338, AbbSum633
	double complex AbbSum710, AbbSum327, AbbSum247, AbbSum243
	double complex AbbSum339, AbbSum252, AbbSum326, AbbSum246
	double complex AbbSum270, AbbSum249, AbbSum1155, AbbSum979
	double complex AbbSum367, AbbSum961, AbbSum971, AbbSum975
	double complex AbbSum967, AbbSum360, AbbSum883, AbbSum1080
	double complex AbbSum1096, AbbSum944, AbbSum994, AbbSum1058
	double complex AbbSum411, AbbSum459, AbbSum1005, AbbSum1014
	double complex AbbSum482, AbbSum1120, AbbSum649, AbbSum1041
	double complex AbbSum636, AbbSum634, AbbSum630, AbbSum711
	double complex AbbSum759, AbbSum765, AbbSum799, AbbSum527
	double complex AbbSum831, AbbSum537, AbbSum500, AbbSum731
	double complex AbbSum899, AbbSum31, AbbSum727, AbbSum755
	double complex AbbSum33, AbbSum28, AbbSum29, AbbSum946
	double complex AbbSum182, AbbSum840, AbbSum813, AbbSum789
	double complex AbbSum416, AbbSum429, AbbSum1131, AbbSum1158
	double complex AbbSum987, AbbSum842, AbbSum453, AbbSum555
	double complex AbbSum784, AbbSum860, AbbSum436, AbbSum847
	double complex AbbSum141, AbbSum543, AbbSum292, AbbSum854
	double complex AbbSum106, AbbSum549, AbbSum364, AbbSum724
	double complex AbbSum607, AbbSum577, AbbSum118, AbbSum957
	double complex AbbSum851, AbbSum187, AbbSum699, AbbSum218
	double complex AbbSum55, AbbSum102, AbbSum720, AbbSum362
	double complex AbbSum526, AbbSum214, AbbSum216, AbbSum405
	double complex AbbSum259, AbbSum1071, AbbSum368, AbbSum365
	double complex AbbSum733, AbbSum1095, AbbSum757, AbbSum576
	double complex AbbSum359, AbbSum725, AbbSum369, AbbSum721
	double complex AbbSum870, AbbSum564, AbbSum419, AbbSum432
	double complex AbbSum871, AbbSum839, AbbSum441, AbbSum559
	double complex AbbSum437, AbbSum426, AbbSum544, AbbSum435
	double complex AbbSum852, AbbSum769, AbbSum565, AbbSum210
	double complex AbbSum307, AbbSum595, AbbSum608, AbbSum610
	double complex AbbSum525, AbbSum479, AbbSum535, AbbSum457
	double complex AbbSum524, AbbSum145, AbbSum566, AbbSum387
	double complex AbbSum75, AbbSum407, AbbSum536, AbbSum579
	double complex AbbSum317, AbbSum865, AbbSum402, AbbSum775
	double complex AbbSum545, AbbSum850, AbbSum603, AbbSum685
	double complex AbbSum297, AbbSum788, AbbSum396, AbbSum830
	double complex AbbSum838, AbbSum662, AbbSum855, AbbSum286
	double complex AbbSum1066, AbbSum206, AbbSum343, AbbSum902
	double complex AbbSum135, AbbSum413, AbbSum983, AbbSum373
	double complex AbbSum119, AbbSum1128, AbbSum1038, AbbSum604
	double complex AbbSum190, AbbSum186, AbbSum447, AbbSum107
	double complex AbbSum109, AbbSum287, AbbSum780, AbbSum1067
	double complex AbbSum357, AbbSum352, AbbSum749, AbbSum512
	double complex AbbSum663, AbbSum551, AbbSum732, AbbSum748
	double complex AbbSum103, AbbSum790, AbbSum787, AbbSum742
	double complex AbbSum863, AbbSum1090, AbbSum1123, AbbSum753
	double complex AbbSum77, AbbSum1048, AbbSum756, AbbSum95
	double complex AbbSum90, AbbSum575, AbbSum609, AbbSum1037
	double complex AbbSum754, AbbSum59, AbbSum800, AbbSum392
	double complex AbbSum380, AbbSum523, AbbSum97, AbbSum845
	double complex AbbSum531, AbbSum415, AbbSum540, AbbSum302
	double complex AbbSum542, AbbSum1015, AbbSum483, AbbSum439
	double complex AbbSum846, AbbSum837, AbbSum425, AbbSum1159
	double complex AbbSum828, AbbSum418, AbbSum431, AbbSum428
	double complex AbbSum409, AbbSum1160, AbbSum520, AbbSum843
	double complex AbbSum541, AbbSum532, AbbSum521, AbbSum528
	double complex AbbSum522, AbbSum558, AbbSum456, AbbSum422
	double complex AbbSum557, AbbSum455, AbbSum460, AbbSum826
	double complex AbbSum213, AbbSum184, AbbSum71, AbbSum312
	double complex AbbSum189, AbbSum836, AbbSum547, AbbSum533
	double complex AbbSum383, AbbSum72, AbbSum93, AbbSum556
	double complex AbbSum434, AbbSum768, AbbSum476, AbbSum454
	double complex AbbSum406, AbbSum861, AbbSum785, AbbSum423
	double complex AbbSum762, AbbSum101, AbbSum519, AbbSum410
	double complex AbbSum215, AbbSum827, AbbSum98, AbbSum763
	double complex AbbSum844, AbbSum835, AbbSum198, AbbSum96
	double complex AbbSum91, AbbSum694, AbbSum534, AbbSum682
	double complex AbbSum395, AbbSum183, AbbSum514, AbbSum386
	double complex AbbSum401, AbbSum398, AbbSum94, AbbSum1132
	double complex AbbSum774, AbbSum446, AbbSum834, AbbSum712
	double complex AbbSum561, AbbSum404, AbbSum258, AbbSum305
	double complex AbbSum341, AbbSum356, AbbSum378, AbbSum323
	double complex AbbSum324, AbbSum217, AbbSum108, AbbSum713
	double complex AbbSum596, AbbSum677, AbbSum306, AbbSum199
	double complex AbbSum89, AbbSum56, AbbSum92, AbbSum345
	double complex AbbSum901, AbbSum351, AbbSum142, AbbSum346
	double complex AbbSum100, AbbSum1070, AbbSum134, AbbSum743
	double complex AbbSum786, AbbSum60, AbbSum862, AbbSum99
	double complex AbbSum412, AbbSum105, AbbSum982, AbbSum372
	double complex AbbSum393, AbbSum104, AbbSum510, AbbSum867
	double complex AbbSum676, AbbSum779, AbbSum229, AbbSum299
	double complex AbbSum154, AbbSum228, AbbSum295, AbbSum153
	double complex AbbSum188, AbbSum910, AbbSum619, AbbSum671
	double complex AbbSum1111, AbbSum878, AbbSum581, AbbSum235
	double complex AbbSum169, AbbSum185, AbbSum909, AbbSum617
	double complex AbbSum669, AbbSum1108, AbbSum877, AbbSum580
	double complex AbbSum234, AbbSum168, AbbSum331, AbbSum244
	double complex AbbSum876, AbbSum585, AbbSum701, AbbSum629
	double complex AbbSum812, AbbSum882, AbbSum897, AbbSum151
	double complex AbbSum904, AbbSum165, AbbSum1030, AbbSum499
	double complex AbbSum330, AbbSum242, AbbSum875, AbbSum583
	double complex AbbSum697, AbbSum628, AbbSum809, AbbSum881
	double complex AbbSum896, AbbSum150, AbbSum903, AbbSum161
	double complex AbbSum1027, AbbSum495, AbbSum73, AbbSum69
	double complex AbbSum74, AbbSum376, AbbSum389, AbbSum370
	double complex AbbSum750, AbbSum34, AbbSum751, AbbSum371
	double complex AbbSum390, AbbSum377, AbbSum32, AbbSum88
	double complex AbbSum374, AbbSum548, AbbSum734, AbbSum170
	double complex AbbSum448, AbbSum468, AbbSum678, AbbSum552
	double complex AbbSum449, AbbSum1156, AbbSum772, AbbSum440
	double complex AbbSum864, AbbSum314, AbbSum781, AbbSum856
	double complex AbbSum708, AbbSum823, AbbSum1024, AbbSum658
	double complex AbbSum1003, AbbSum572, AbbSum132, AbbSum848
	double complex AbbSum375, AbbSum1130, AbbSum673, AbbSum1011
	double complex AbbSum1002, AbbSum992, AbbSum773, AbbSum550
	double complex AbbSum515, AbbSum480, AbbSum504, AbbSum822
	double complex AbbSum256, AbbSum1000, AbbSum282, AbbSum735
	double complex AbbSum991, AbbSum1012, AbbSum1009, AbbSum1010
	double complex AbbSum849, AbbSum1045, AbbSum178, AbbSum679
	double complex AbbSum1086, AbbSum112, AbbSum573, AbbSum829
	double complex AbbSum1077, AbbSum553, AbbSum438, AbbSum466
	double complex AbbSum442, AbbSum1025, AbbSum1144, AbbSum503
	double complex AbbSum451, AbbSum1126, AbbSum1161, AbbSum672
	double complex AbbSum465, AbbSum458, AbbSum702, AbbSum502
	double complex AbbSum652, AbbSum467, AbbSum172, AbbSum794
	double complex AbbSum194, AbbSum303, AbbSum308, AbbSum450
	double complex AbbSum274, AbbSum332, AbbSum130, AbbSum260
	double complex AbbSum276, AbbSum115, AbbSum1148, AbbSum469
	double complex AbbSum1137, AbbSum481, AbbSum470, AbbSum193
	double complex AbbSum858, AbbSum471, AbbSum821, AbbSum984
	double complex AbbSum443, AbbSum1072, AbbSum171, AbbSum261
	double complex AbbSum461, AbbSum1092, AbbSum516, AbbSum776
	double complex AbbSum998, AbbSum462, AbbSum501, AbbSum333
	double complex AbbSum1147, AbbSum985, AbbSum791, AbbSum1039
	double complex AbbSum1118, AbbSum275, AbbSum782, AbbSum304
	double complex AbbSum857, AbbSum999, AbbSum980, AbbSum463
	double complex AbbSum808, AbbSum1125, AbbSum1082, AbbSum272
	double complex AbbSum290, AbbSum1068, AbbSum792, AbbSum1022
	double complex AbbSum582, AbbSum1097, AbbSum1044, AbbSum1075
	double complex AbbSum571, AbbSum797, AbbSum1107, AbbSum650
	double complex AbbSum131, AbbSum693, AbbSum873, AbbSum1017
	double complex AbbSum893, AbbSum770, AbbSum657, AbbSum645
	double complex AbbSum567, AbbSum1088, AbbSum1104, AbbSum1122
	double complex AbbSum954, AbbSum1051, AbbSum1055, AbbSum1106
	double complex AbbSum116, AbbSum639, AbbSum667, AbbSum688
	double complex AbbSum959, AbbSum973, AbbSum666, AbbSum253
	double complex AbbSum265, AbbSum444, AbbSum146, AbbSum996
	double complex AbbSum147, AbbSum255, AbbSum291, AbbSum139
	double complex AbbSum695, AbbSum962, AbbSum692, AbbSum486
	double complex AbbSum1033, AbbSum1023, AbbSum507, AbbSum816
	double complex AbbSum1135, AbbSum176, AbbSum1089, AbbSum140
	double complex AbbSum706, AbbSum493, AbbSum977, AbbSum1151
	double complex AbbSum494, AbbSum817, AbbSum806, AbbSum1034
	double complex AbbSum473, AbbSum1142, AbbSum1114, AbbSum1113
	double complex AbbSum1141, AbbSum491, AbbSum475, AbbSum805
	double complex AbbSum508, AbbSum591, AbbSum1021, AbbSum160
	double complex AbbSum1140, AbbSum159, AbbSum281, AbbSum637
	double complex AbbSum646, AbbSum158, AbbSum1098, AbbSum926
	double complex AbbSum936, AbbSum777, AbbSum328, AbbSum315
	double complex AbbSum316, AbbSum293, AbbSum267, AbbSum113
	double complex AbbSum322, AbbSum1007, AbbSum1059, AbbSum988
	double complex AbbSum490, AbbSum1006, AbbSum1084, AbbSum1001
	double complex AbbSum818, AbbSum798, AbbSum487, AbbSum981
	double complex AbbSum1105, AbbSum464, AbbSum1129, AbbSum1083
	double complex AbbSum273, AbbSum1136, AbbSum696, AbbSum294
	double complex AbbSum177, AbbSum1081, AbbSum1069, AbbSum793
	double complex AbbSum1100, AbbSum1029, AbbSum1046, AbbSum584
	double complex AbbSum1091, AbbSum509, AbbSum264, AbbSum311
	double complex AbbSum57, AbbSum271, AbbSum58, AbbSum204
	double complex AbbSum205, AbbSum1079, AbbSum651, AbbSum1110
	double complex AbbSum574, AbbSum133, AbbSum995, AbbSum874
	double complex AbbSum257, AbbSum143, AbbSum1036, AbbSum771
	double complex AbbSum640, AbbSum963, AbbSum659, AbbSum445
	double complex AbbSum1018, AbbSum117, AbbSum296, AbbSum700
	double complex AbbSum647, AbbSum670, AbbSum254, AbbSum698
	double complex AbbSum568, AbbSum268, AbbSum148, AbbSum689
	double complex AbbSum997, AbbSum149, AbbSum1094, AbbSum1109
	double complex AbbSum894, AbbSum1127, AbbSum511, AbbSum474
	double complex AbbSum1026, AbbSum279, AbbSum336, AbbSum1061
	double complex AbbSum684, AbbSum990, AbbSum644, AbbSum947
	double complex AbbSum48, AbbSum570, AbbSum943, AbbSum80
	double complex AbbSum965, AbbSum942, AbbSum78, AbbSum79
	double complex AbbSum683, AbbSum643, AbbSum1042, AbbSum1060
	double complex AbbSum989, AbbSum655, AbbSum144, AbbSum705
	double complex AbbSum498, AbbSum497, AbbSum709, AbbSum1154
	double complex AbbSum329, AbbSum1043, AbbSum656, AbbSum707
	double complex AbbSum819, AbbSum811, AbbSum1052, AbbSum1035
	double complex AbbSum1056, AbbSum1117, AbbSum1146, AbbSum1152
	double complex AbbSum478, AbbSum496, AbbSum810, AbbSum668
	double complex AbbSum1143, AbbSum1121, AbbSum638, AbbSum164
	double complex AbbSum283, AbbSum1115, AbbSum648, AbbSum1028
	double complex AbbSum592, AbbSum163, AbbSum955, AbbSum162
	double complex AbbSum1145, AbbSum978, AbbSum960, AbbSum974
	double complex AbbSum600, AbbSum599, AbbSum83, AbbSum81
	double complex AbbSum54, AbbSum82, AbbSum1076, AbbSum1101
	double complex AbbSum318, AbbSum319, AbbSum269, AbbSum325
	double complex AbbSum778, AbbSum114, AbbSum928, AbbSum298
	double complex AbbSum938, AbbSum1074, AbbSum948, AbbSum966
	double complex AbbSum931, AbbSum129, AbbSum930, AbbSum1062
	double complex AbbSum993, AbbSum337, AbbSum280, AbbSum313
	double complex AbbSum266, AbbSum807, AbbSum1013, AbbSum492
	double complex AbbSum1124, AbbSum1085, AbbSum1008, AbbSum1153
	common /abbrev/ F3, F6, F35, F37, F49, F38, F40, F41, F110
	common /abbrev/ F120, F121, F111, F122, F123, F36, F39, Pair4
	common /abbrev/ Pair8, Pair11, Pair9, Pair10, Eps12, Eps13
	common /abbrev/ Abb14, Abb15, Abb84, Abb85, Abb86, Abb87
	common /abbrev/ Abb22, Abb23, Abb124, Abb125, Abb42, Abb50
	common /abbrev/ Abb126, Abb127, Abb43, Abb51, Abb16, Abb61
	common /abbrev/ Abb62, Abb24, Abb5, Abb44, Abb52, Abb7, Abb136
	common /abbrev/ Abb137, Abb53, Abb45, Abb17, Abb63, Abb64
	common /abbrev/ Abb25, Abb155, Abb156, Abb46, Abb47, Abb18
	common /abbrev/ Abb65, Abb66, Abb26, Abb19, Abb67, Abb68
	common /abbrev/ Abb27, AbbSum379, AbbSum381, AbbSum968
	common /abbrev/ AbbSum716, AbbSum949, AbbSum801, AbbSum1099
	common /abbrev/ AbbSum802, AbbSum969, AbbSum717, AbbSum950
	common /abbrev/ AbbSum872, AbbSum578, AbbSum925, AbbSum939
	common /abbrev/ AbbSum920, AbbSum923, AbbSum935, AbbSum361
	common /abbrev/ AbbSum385, AbbSum220, AbbSum340, AbbSum202
	common /abbrev/ AbbSum348, AbbSum344, AbbSum354, AbbSum417
	common /abbrev/ AbbSum350, AbbSum208, AbbSum933, AbbSum929
	common /abbrev/ AbbSum430, AbbSum400, AbbSum397, AbbSum421
	common /abbrev/ AbbSum382, AbbSum766, AbbSum744, AbbSum746
	common /abbrev/ AbbSum953, AbbSum885, AbbSum614, AbbSum612
	common /abbrev/ AbbSum620, AbbSum616, AbbSum391, AbbSum718
	common /abbrev/ AbbSum740, AbbSum728, AbbSum597, AbbSum760
	common /abbrev/ AbbSum951, AbbSum736, AbbSum714, AbbSum738
	common /abbrev/ AbbSum722, AbbSum602, AbbSum890, AbbSum245
	common /abbrev/ AbbSum241, AbbSum250, AbbSum248, AbbSum976
	common /abbrev/ AbbSum366, AbbSum958, AbbSum970, AbbSum972
	common /abbrev/ AbbSum964, AbbSum358, AbbSum1112, AbbSum1073
	common /abbrev/ AbbSum1087, AbbSum941, AbbSum408, AbbSum472
	common /abbrev/ AbbSum635, AbbSum758, AbbSum764, AbbSum730
	common /abbrev/ AbbSum30, AbbSum726, AbbSum20, AbbSum21
	common /abbrev/ AbbSum752, AbbSum945, AbbSum414, AbbSum427
	common /abbrev/ AbbSum76, AbbSum284, AbbSum222, AbbSum179
	common /abbrev/ AbbSum911, AbbSum660, AbbSum224, AbbSum200
	common /abbrev/ AbbSum664, AbbSum686, AbbSum1064, AbbSum562
	common /abbrev/ AbbSum868, AbbSum986, AbbSum927, AbbSum940
	common /abbrev/ AbbSum922, AbbSum924, AbbSum937, AbbSum209
	common /abbrev/ AbbSum892, AbbSum1063, AbbSum921, AbbSum1057
	common /abbrev/ AbbSum1065, AbbSum506, AbbSum309, AbbSum174
	common /abbrev/ AbbSum484, AbbSum300, AbbSum334, AbbSum262
	common /abbrev/ AbbSum1149, AbbSum180, AbbSum912, AbbSum152
	common /abbrev/ AbbSum1016, AbbSum223, AbbSum236, AbbSum277
	common /abbrev/ AbbSum285, AbbSum173, AbbSum485, AbbSum505
	common /abbrev/ AbbSum1032, AbbSum452, AbbSum554, AbbSum320
	common /abbrev/ AbbSum227, AbbSum289, AbbSum363, AbbSum388
	common /abbrev/ AbbSum212, AbbSum230, AbbSum1004, AbbSum221
	common /abbrev/ AbbSum231, AbbSum219, AbbSum342, AbbSum207
	common /abbrev/ AbbSum349, AbbSum347, AbbSum175, AbbSum128
	common /abbrev/ AbbSum513, AbbSum138, AbbSum355, AbbSum420
	common /abbrev/ AbbSum353, AbbSum211, AbbSum934, AbbSum932
	common /abbrev/ AbbSum560, AbbSum203, AbbSum288, AbbSum226
	common /abbrev/ AbbSum321, AbbSum1031, AbbSum563, AbbSum1133
	common /abbrev/ AbbSum687, AbbSum1050, AbbSum1054, AbbSum841
	common /abbrev/ AbbSum916, AbbSum631, AbbSum1102, AbbSum593
	common /abbrev/ AbbSum665, AbbSum919, AbbSum433, AbbSum403
	common /abbrev/ AbbSum399, AbbSum538, AbbSum815, AbbSum914
	common /abbrev/ AbbSum887, AbbSum626, AbbSum641, AbbSum905
	common /abbrev/ AbbSum915, AbbSum588, AbbSum589, AbbSum879
	common /abbrev/ AbbSum586, AbbSum680, AbbSum622, AbbSum653
	common /abbrev/ AbbSum624, AbbSum907, AbbSum661, AbbSum166
	common /abbrev/ AbbSum232, AbbSum225, AbbSum239, AbbSum201
	common /abbrev/ AbbSum191, AbbSum195, AbbSum674, AbbSum703
	common /abbrev/ AbbSum690, AbbSum424, AbbSum384, AbbSum814
	common /abbrev/ AbbSum917, AbbSum918, AbbSum1103, AbbSum795
	common /abbrev/ AbbSum767, AbbSum745, AbbSum747, AbbSum1053
	common /abbrev/ AbbSum1049, AbbSum1138, AbbSum1134, AbbSum783
	common /abbrev/ AbbSum859, AbbSum546, AbbSum956, AbbSum886
	common /abbrev/ AbbSum606, AbbSum884, AbbSum615, AbbSum613
	common /abbrev/ AbbSum611, AbbSum913, AbbSum1047, AbbSum621
	common /abbrev/ AbbSum618, AbbSum394, AbbSum719, AbbSum741
	common /abbrev/ AbbSum729, AbbSum601, AbbSum761, AbbSum952
	common /abbrev/ AbbSum737, AbbSum715, AbbSum739, AbbSum590
	common /abbrev/ AbbSum569, AbbSum820, AbbSum723, AbbSum605
	common /abbrev/ AbbSum866, AbbSum598, AbbSum1119, AbbSum1040
	common /abbrev/ AbbSum237, AbbSum197, AbbSum853, AbbSum869
	common /abbrev/ AbbSum477, AbbSum539, AbbSum824, AbbSum796
	common /abbrev/ AbbSum517, AbbSum704, AbbSum691, AbbSum1020
	common /abbrev/ AbbSum1139, AbbSum803, AbbSum833, AbbSum488
	common /abbrev/ AbbSum529, AbbSum263, AbbSum888, AbbSum240
	common /abbrev/ AbbSum1078, AbbSum880, AbbSum1150, AbbSum238
	common /abbrev/ AbbSum278, AbbSum906, AbbSum898, AbbSum196
	common /abbrev/ AbbSum192, AbbSum587, AbbSum900, AbbSum908
	common /abbrev/ AbbSum895, AbbSum70, AbbSum181, AbbSum157
	common /abbrev/ AbbSum627, AbbSum625, AbbSum642, AbbSum654
	common /abbrev/ AbbSum623, AbbSum675, AbbSum681, AbbSum489
	common /abbrev/ AbbSum530, AbbSum832, AbbSum804, AbbSum335
	common /abbrev/ AbbSum1019, AbbSum233, AbbSum594, AbbSum167
	common /abbrev/ AbbSum825, AbbSum518, AbbSum632, AbbSum301
	common /abbrev/ AbbSum1116, AbbSum310, AbbSum1157, AbbSum1093
	common /abbrev/ AbbSum891, AbbSum251, AbbSum889, AbbSum338
	common /abbrev/ AbbSum633, AbbSum710, AbbSum327, AbbSum247
	common /abbrev/ AbbSum243, AbbSum339, AbbSum252, AbbSum326
	common /abbrev/ AbbSum246, AbbSum270, AbbSum249, AbbSum1155
	common /abbrev/ AbbSum979, AbbSum367, AbbSum961, AbbSum971
	common /abbrev/ AbbSum975, AbbSum967, AbbSum360, AbbSum883
	common /abbrev/ AbbSum1080, AbbSum1096, AbbSum944, AbbSum994
	common /abbrev/ AbbSum1058, AbbSum411, AbbSum459, AbbSum1005
	common /abbrev/ AbbSum1014, AbbSum482, AbbSum1120, AbbSum649
	common /abbrev/ AbbSum1041, AbbSum636, AbbSum634, AbbSum630
	common /abbrev/ AbbSum711, AbbSum759, AbbSum765, AbbSum799
	common /abbrev/ AbbSum527, AbbSum831, AbbSum537, AbbSum500
	common /abbrev/ AbbSum731, AbbSum899, AbbSum31, AbbSum727
	common /abbrev/ AbbSum755, AbbSum33, AbbSum28, AbbSum29
	common /abbrev/ AbbSum946, AbbSum182, AbbSum840, AbbSum813
	common /abbrev/ AbbSum789, AbbSum416, AbbSum429, AbbSum1131
	common /abbrev/ AbbSum1158, AbbSum987, AbbSum842, AbbSum453
	common /abbrev/ AbbSum555, AbbSum784, AbbSum860, AbbSum436
	common /abbrev/ AbbSum847, AbbSum141, AbbSum543, AbbSum292
	common /abbrev/ AbbSum854, AbbSum106, AbbSum549, AbbSum364
	common /abbrev/ AbbSum724, AbbSum607, AbbSum577, AbbSum118
	common /abbrev/ AbbSum957, AbbSum851, AbbSum187, AbbSum699
	common /abbrev/ AbbSum218, AbbSum55, AbbSum102, AbbSum720
	common /abbrev/ AbbSum362, AbbSum526, AbbSum214, AbbSum216
	common /abbrev/ AbbSum405, AbbSum259, AbbSum1071, AbbSum368
	common /abbrev/ AbbSum365, AbbSum733, AbbSum1095, AbbSum757
	common /abbrev/ AbbSum576, AbbSum359, AbbSum725, AbbSum369
	common /abbrev/ AbbSum721, AbbSum870, AbbSum564, AbbSum419
	common /abbrev/ AbbSum432, AbbSum871, AbbSum839, AbbSum441
	common /abbrev/ AbbSum559, AbbSum437, AbbSum426, AbbSum544
	common /abbrev/ AbbSum435, AbbSum852, AbbSum769, AbbSum565
	common /abbrev/ AbbSum210, AbbSum307, AbbSum595, AbbSum608
	common /abbrev/ AbbSum610, AbbSum525, AbbSum479, AbbSum535
	common /abbrev/ AbbSum457, AbbSum524, AbbSum145, AbbSum566
	common /abbrev/ AbbSum387, AbbSum75, AbbSum407, AbbSum536
	common /abbrev/ AbbSum579, AbbSum317, AbbSum865, AbbSum402
	common /abbrev/ AbbSum775, AbbSum545, AbbSum850, AbbSum603
	common /abbrev/ AbbSum685, AbbSum297, AbbSum788, AbbSum396
	common /abbrev/ AbbSum830, AbbSum838, AbbSum662, AbbSum855
	common /abbrev/ AbbSum286, AbbSum1066, AbbSum206, AbbSum343
	common /abbrev/ AbbSum902, AbbSum135, AbbSum413, AbbSum983
	common /abbrev/ AbbSum373, AbbSum119, AbbSum1128, AbbSum1038
	common /abbrev/ AbbSum604, AbbSum190, AbbSum186, AbbSum447
	common /abbrev/ AbbSum107, AbbSum109, AbbSum287, AbbSum780
	common /abbrev/ AbbSum1067, AbbSum357, AbbSum352, AbbSum749
	common /abbrev/ AbbSum512, AbbSum663, AbbSum551, AbbSum732
	common /abbrev/ AbbSum748, AbbSum103, AbbSum790, AbbSum787
	common /abbrev/ AbbSum742, AbbSum863, AbbSum1090, AbbSum1123
	common /abbrev/ AbbSum753, AbbSum77, AbbSum1048, AbbSum756
	common /abbrev/ AbbSum95, AbbSum90, AbbSum575, AbbSum609
	common /abbrev/ AbbSum1037, AbbSum754, AbbSum59, AbbSum800
	common /abbrev/ AbbSum392, AbbSum380, AbbSum523, AbbSum97
	common /abbrev/ AbbSum845, AbbSum531, AbbSum415, AbbSum540
	common /abbrev/ AbbSum302, AbbSum542, AbbSum1015, AbbSum483
	common /abbrev/ AbbSum439, AbbSum846, AbbSum837, AbbSum425
	common /abbrev/ AbbSum1159, AbbSum828, AbbSum418, AbbSum431
	common /abbrev/ AbbSum428, AbbSum409, AbbSum1160, AbbSum520
	common /abbrev/ AbbSum843, AbbSum541, AbbSum532, AbbSum521
	common /abbrev/ AbbSum528, AbbSum522, AbbSum558, AbbSum456
	common /abbrev/ AbbSum422, AbbSum557, AbbSum455, AbbSum460
	common /abbrev/ AbbSum826, AbbSum213, AbbSum184, AbbSum71
	common /abbrev/ AbbSum312, AbbSum189, AbbSum836, AbbSum547
	common /abbrev/ AbbSum533, AbbSum383, AbbSum72, AbbSum93
	common /abbrev/ AbbSum556, AbbSum434, AbbSum768, AbbSum476
	common /abbrev/ AbbSum454, AbbSum406, AbbSum861, AbbSum785
	common /abbrev/ AbbSum423, AbbSum762, AbbSum101, AbbSum519
	common /abbrev/ AbbSum410, AbbSum215, AbbSum827, AbbSum98
	common /abbrev/ AbbSum763, AbbSum844, AbbSum835, AbbSum198
	common /abbrev/ AbbSum96, AbbSum91, AbbSum694, AbbSum534
	common /abbrev/ AbbSum682, AbbSum395, AbbSum183, AbbSum514
	common /abbrev/ AbbSum386, AbbSum401, AbbSum398, AbbSum94
	common /abbrev/ AbbSum1132, AbbSum774, AbbSum446, AbbSum834
	common /abbrev/ AbbSum712, AbbSum561, AbbSum404, AbbSum258
	common /abbrev/ AbbSum305, AbbSum341, AbbSum356, AbbSum378
	common /abbrev/ AbbSum323, AbbSum324, AbbSum217, AbbSum108
	common /abbrev/ AbbSum713, AbbSum596, AbbSum677, AbbSum306
	common /abbrev/ AbbSum199, AbbSum89, AbbSum56, AbbSum92
	common /abbrev/ AbbSum345, AbbSum901, AbbSum351, AbbSum142
	common /abbrev/ AbbSum346, AbbSum100, AbbSum1070, AbbSum134
	common /abbrev/ AbbSum743, AbbSum786, AbbSum60, AbbSum862
	common /abbrev/ AbbSum99, AbbSum412, AbbSum105, AbbSum982
	common /abbrev/ AbbSum372, AbbSum393, AbbSum104, AbbSum510
	common /abbrev/ AbbSum867, AbbSum676, AbbSum779, AbbSum229
	common /abbrev/ AbbSum299, AbbSum154, AbbSum228, AbbSum295
	common /abbrev/ AbbSum153, AbbSum188, AbbSum910, AbbSum619
	common /abbrev/ AbbSum671, AbbSum1111, AbbSum878, AbbSum581
	common /abbrev/ AbbSum235, AbbSum169, AbbSum185, AbbSum909
	common /abbrev/ AbbSum617, AbbSum669, AbbSum1108, AbbSum877
	common /abbrev/ AbbSum580, AbbSum234, AbbSum168, AbbSum331
	common /abbrev/ AbbSum244, AbbSum876, AbbSum585, AbbSum701
	common /abbrev/ AbbSum629, AbbSum812, AbbSum882, AbbSum897
	common /abbrev/ AbbSum151, AbbSum904, AbbSum165, AbbSum1030
	common /abbrev/ AbbSum499, AbbSum330, AbbSum242, AbbSum875
	common /abbrev/ AbbSum583, AbbSum697, AbbSum628, AbbSum809
	common /abbrev/ AbbSum881, AbbSum896, AbbSum150, AbbSum903
	common /abbrev/ AbbSum161, AbbSum1027, AbbSum495, AbbSum73
	common /abbrev/ AbbSum69, AbbSum74, AbbSum376, AbbSum389
	common /abbrev/ AbbSum370, AbbSum750, AbbSum34, AbbSum751
	common /abbrev/ AbbSum371, AbbSum390, AbbSum377, AbbSum32
	common /abbrev/ AbbSum88, AbbSum374, AbbSum548, AbbSum734
	common /abbrev/ AbbSum170, AbbSum448, AbbSum468, AbbSum678
	common /abbrev/ AbbSum552, AbbSum449, AbbSum1156, AbbSum772
	common /abbrev/ AbbSum440, AbbSum864, AbbSum314, AbbSum781
	common /abbrev/ AbbSum856, AbbSum708, AbbSum823, AbbSum1024
	common /abbrev/ AbbSum658, AbbSum1003, AbbSum572, AbbSum132
	common /abbrev/ AbbSum848, AbbSum375, AbbSum1130, AbbSum673
	common /abbrev/ AbbSum1011, AbbSum1002, AbbSum992, AbbSum773
	common /abbrev/ AbbSum550, AbbSum515, AbbSum480, AbbSum504
	common /abbrev/ AbbSum822, AbbSum256, AbbSum1000, AbbSum282
	common /abbrev/ AbbSum735, AbbSum991, AbbSum1012, AbbSum1009
	common /abbrev/ AbbSum1010, AbbSum849, AbbSum1045, AbbSum178
	common /abbrev/ AbbSum679, AbbSum1086, AbbSum112, AbbSum573
	common /abbrev/ AbbSum829, AbbSum1077, AbbSum553, AbbSum438
	common /abbrev/ AbbSum466, AbbSum442, AbbSum1025, AbbSum1144
	common /abbrev/ AbbSum503, AbbSum451, AbbSum1126, AbbSum1161
	common /abbrev/ AbbSum672, AbbSum465, AbbSum458, AbbSum702
	common /abbrev/ AbbSum502, AbbSum652, AbbSum467, AbbSum172
	common /abbrev/ AbbSum794, AbbSum194, AbbSum303, AbbSum308
	common /abbrev/ AbbSum450, AbbSum274, AbbSum332, AbbSum130
	common /abbrev/ AbbSum260, AbbSum276, AbbSum115, AbbSum1148
	common /abbrev/ AbbSum469, AbbSum1137, AbbSum481, AbbSum470
	common /abbrev/ AbbSum193, AbbSum858, AbbSum471, AbbSum821
	common /abbrev/ AbbSum984, AbbSum443, AbbSum1072, AbbSum171
	common /abbrev/ AbbSum261, AbbSum461, AbbSum1092, AbbSum516
	common /abbrev/ AbbSum776, AbbSum998, AbbSum462, AbbSum501
	common /abbrev/ AbbSum333, AbbSum1147, AbbSum985, AbbSum791
	common /abbrev/ AbbSum1039, AbbSum1118, AbbSum275, AbbSum782
	common /abbrev/ AbbSum304, AbbSum857, AbbSum999, AbbSum980
	common /abbrev/ AbbSum463, AbbSum808, AbbSum1125, AbbSum1082
	common /abbrev/ AbbSum272, AbbSum290, AbbSum1068, AbbSum792
	common /abbrev/ AbbSum1022, AbbSum582, AbbSum1097, AbbSum1044
	common /abbrev/ AbbSum1075, AbbSum571, AbbSum797, AbbSum1107
	common /abbrev/ AbbSum650, AbbSum131, AbbSum693, AbbSum873
	common /abbrev/ AbbSum1017, AbbSum893, AbbSum770, AbbSum657
	common /abbrev/ AbbSum645, AbbSum567, AbbSum1088, AbbSum1104
	common /abbrev/ AbbSum1122, AbbSum954, AbbSum1051, AbbSum1055
	common /abbrev/ AbbSum1106, AbbSum116, AbbSum639, AbbSum667
	common /abbrev/ AbbSum688, AbbSum959, AbbSum973, AbbSum666
	common /abbrev/ AbbSum253, AbbSum265, AbbSum444, AbbSum146
	common /abbrev/ AbbSum996, AbbSum147, AbbSum255, AbbSum291
	common /abbrev/ AbbSum139, AbbSum695, AbbSum962, AbbSum692
	common /abbrev/ AbbSum486, AbbSum1033, AbbSum1023, AbbSum507
	common /abbrev/ AbbSum816, AbbSum1135, AbbSum176, AbbSum1089
	common /abbrev/ AbbSum140, AbbSum706, AbbSum493, AbbSum977
	common /abbrev/ AbbSum1151, AbbSum494, AbbSum817, AbbSum806
	common /abbrev/ AbbSum1034, AbbSum473, AbbSum1142, AbbSum1114
	common /abbrev/ AbbSum1113, AbbSum1141, AbbSum491, AbbSum475
	common /abbrev/ AbbSum805, AbbSum508, AbbSum591, AbbSum1021
	common /abbrev/ AbbSum160, AbbSum1140, AbbSum159, AbbSum281
	common /abbrev/ AbbSum637, AbbSum646, AbbSum158, AbbSum1098
	common /abbrev/ AbbSum926, AbbSum936, AbbSum777, AbbSum328
	common /abbrev/ AbbSum315, AbbSum316, AbbSum293, AbbSum267
	common /abbrev/ AbbSum113, AbbSum322, AbbSum1007, AbbSum1059
	common /abbrev/ AbbSum988, AbbSum490, AbbSum1006, AbbSum1084
	common /abbrev/ AbbSum1001, AbbSum818, AbbSum798, AbbSum487
	common /abbrev/ AbbSum981, AbbSum1105, AbbSum464, AbbSum1129
	common /abbrev/ AbbSum1083, AbbSum273, AbbSum1136, AbbSum696
	common /abbrev/ AbbSum294, AbbSum177, AbbSum1081, AbbSum1069
	common /abbrev/ AbbSum793, AbbSum1100, AbbSum1029, AbbSum1046
	common /abbrev/ AbbSum584, AbbSum1091, AbbSum509, AbbSum264
	common /abbrev/ AbbSum311, AbbSum57, AbbSum271, AbbSum58
	common /abbrev/ AbbSum204, AbbSum205, AbbSum1079, AbbSum651
	common /abbrev/ AbbSum1110, AbbSum574, AbbSum133, AbbSum995
	common /abbrev/ AbbSum874, AbbSum257, AbbSum143, AbbSum1036
	common /abbrev/ AbbSum771, AbbSum640, AbbSum963, AbbSum659
	common /abbrev/ AbbSum445, AbbSum1018, AbbSum117, AbbSum296
	common /abbrev/ AbbSum700, AbbSum647, AbbSum670, AbbSum254
	common /abbrev/ AbbSum698, AbbSum568, AbbSum268, AbbSum148
	common /abbrev/ AbbSum689, AbbSum997, AbbSum149, AbbSum1094
	common /abbrev/ AbbSum1109, AbbSum894, AbbSum1127, AbbSum511
	common /abbrev/ AbbSum474, AbbSum1026, AbbSum279, AbbSum336
	common /abbrev/ AbbSum1061, AbbSum684, AbbSum990, AbbSum644
	common /abbrev/ AbbSum947, AbbSum48, AbbSum570, AbbSum943
	common /abbrev/ AbbSum80, AbbSum965, AbbSum942, AbbSum78
	common /abbrev/ AbbSum79, AbbSum683, AbbSum643, AbbSum1042
	common /abbrev/ AbbSum1060, AbbSum989, AbbSum655, AbbSum144
	common /abbrev/ AbbSum705, AbbSum498, AbbSum497, AbbSum709
	common /abbrev/ AbbSum1154, AbbSum329, AbbSum1043, AbbSum656
	common /abbrev/ AbbSum707, AbbSum819, AbbSum811, AbbSum1052
	common /abbrev/ AbbSum1035, AbbSum1056, AbbSum1117, AbbSum1146
	common /abbrev/ AbbSum1152, AbbSum478, AbbSum496, AbbSum810
	common /abbrev/ AbbSum668, AbbSum1143, AbbSum1121, AbbSum638
	common /abbrev/ AbbSum164, AbbSum283, AbbSum1115, AbbSum648
	common /abbrev/ AbbSum1028, AbbSum592, AbbSum163, AbbSum955
	common /abbrev/ AbbSum162, AbbSum1145, AbbSum978, AbbSum960
	common /abbrev/ AbbSum974, AbbSum600, AbbSum599, AbbSum83
	common /abbrev/ AbbSum81, AbbSum54, AbbSum82, AbbSum1076
	common /abbrev/ AbbSum1101, AbbSum318, AbbSum319, AbbSum269
	common /abbrev/ AbbSum325, AbbSum778, AbbSum114, AbbSum928
	common /abbrev/ AbbSum298, AbbSum938, AbbSum1074, AbbSum948
	common /abbrev/ AbbSum966, AbbSum931, AbbSum129, AbbSum930
	common /abbrev/ AbbSum1062, AbbSum993, AbbSum337, AbbSum280
	common /abbrev/ AbbSum313, AbbSum266, AbbSum807, AbbSum1013
	common /abbrev/ AbbSum492, AbbSum1124, AbbSum1085, AbbSum1008
	common /abbrev/ AbbSum1153

	integer*8 iint1,iint2,iint3,iint4(3),iint5(3),iint6(3)
	integer*8 iint7(3),iint8(3),iint9(3),iint10(3),iint11(3)
	integer*8 iint12(3),iint13(3),iint14(3),iint15(3),iint16(2)
	integer*8 iint17(2),iint18,iint19,iint20(3),iint21(3)
	integer*8 iint22(3),iint23(3),iint24(3),iint25(3),iint26(3)
	integer*8 iint27(3),iint28(3),iint29(3),iint30(3),iint31(3)
	integer*8 iint32(3),iint33(3),iint34(3),iint35(3),iint36(3)
	integer*8 iint37(3),iint38(3),iint39(3),iint40(3),iint41(3)
	integer*8 iint42(3),iint43(3),iint44(3),iint45(3),iint46(3)
	integer*8 iint47(3),iint48(3),iint49(3),iint50(3),iint51(3)
	integer*8 iint52(3),iint53(3),iint54(3),iint55(3),iint56(3)
	integer*8 iint57(3),iint58(3),iint59(3),iint60(3),iint61(3)
	integer*8 iint62(3),iint63(3),iint64(3),iint65(3),iint66(3)
	integer*8 iint67(3),iint68(3),iint69(3),iint70(3),iint71(3)
	integer*8 iint72(3),iint73(3),iint74(3),iint75(3),iint76(3)
	integer*8 iint77(2),iint78(2),iint79(2),iint80(2),iint81(2)
	integer*8 iint82(2),iint83(2),iint84(2),iint85(2),iint86(2)
	integer*8 iint87(2),iint88(2),iint89(2),iint90(2),iint91(2)
	integer*8 iint92(2),iint93,iint94(2),iint95(2),iint96(2)
	integer*8 iint97(2),iint98(2),iint99(2),iint100(2)
	integer*8 iint101(2),iint102(2)
	common /loopint/ iint1,iint2,iint3,iint4,iint5,iint6
	common /loopint/ iint7,iint8,iint9,iint10,iint11,iint12
	common /loopint/ iint13,iint14,iint15,iint16,iint17
	common /loopint/ iint18,iint19,iint20,iint21,iint22
	common /loopint/ iint23,iint24,iint25,iint26,iint27
	common /loopint/ iint28,iint29,iint30,iint31,iint32
	common /loopint/ iint33,iint34,iint35,iint36,iint37
	common /loopint/ iint38,iint39,iint40,iint41,iint42
	common /loopint/ iint43,iint44,iint45,iint46,iint47
	common /loopint/ iint48,iint49,iint50,iint51,iint52
	common /loopint/ iint53,iint54,iint55,iint56,iint57
	common /loopint/ iint58,iint59,iint60,iint61,iint62
	common /loopint/ iint63,iint64,iint65,iint66,iint67
	common /loopint/ iint68,iint69,iint70,iint71,iint72
	common /loopint/ iint73,iint74,iint75,iint76,iint77
	common /loopint/ iint78,iint79,iint80,iint81,iint82
	common /loopint/ iint83,iint84,iint85,iint86,iint87
	common /loopint/ iint88,iint89,iint90,iint91,iint92
	common /loopint/ iint93,iint94,iint95,iint96,iint97
	common /loopint/ iint98,iint99,iint100,iint101,iint102

	integer cha5, hia5, his5, ij, lpd5, qud5, quu5, sld5, sle5
	integer sqd5, sqe5, squ5, sqv5
	common /indices/ cha5, hia5, his5, ij, lpd5, qud5, quu5, sld5
	common /indices/ sle5, sqd5, sqe5, squ5, sqv5

	double complex Cloop(1)
	common /formfactors/ Cloop

