DDW- |~B1  |~t1  |     |Zt11*Zb11*Maux*EE*Sqrt2/(2*SW)                    |1
DDW- |~B1  |~t2  |     |Zt21*Zb11*Maux*EE*Sqrt2/(2*SW)                    |1
DDW- |~B2  |~t1  |     |Zt11*Zb21*Maux*EE*Sqrt2/(2*SW)                    |1
DDW- |~B2  |~t2  |     |Zt21*Zb21*Maux*EE*Sqrt2/(2*SW)                    |1
DDW+ |~CL  |~sL  |     |Maux*EE*Sqrt2/(2*SW)                              |1
DDW- |~DL  |~uL  |     |Maux*EE*Sqrt2/(2*SW)                              |1
DDW- |~EL  |~ne  |     |Maux*EE*Sqrt2/(2*SW)                              |1
DDW- |~L1  |~nl  |     |Zl11*Maux*EE*Sqrt2/(2*SW)                         |1
DDW- |~L2  |~nl  |     |Zl21*Maux*EE*Sqrt2/(2*SW)                         |1
DDW- |~ML  |~nm  |     |Maux*EE*Sqrt2/(2*SW)                              |1
DDW+ |~Ne  |~eL  |     |Maux*EE*Sqrt2/(2*SW)                              |1
DDW+ |~Nl  |~l1  |     |Zl11*Maux*EE*Sqrt2/(2*SW)                         |1
DDW+ |~Nl  |~l2  |     |Zl21*Maux*EE*Sqrt2/(2*SW)                         |1
DDW+ |~Nm  |~mL  |     |Maux*EE*Sqrt2/(2*SW)                              |1
DDW- |~SL  |~cL  |     |Maux*EE*Sqrt2/(2*SW)                              |1
DDW+ |~T1  |~b1  |     |Zt11*Zb11*Maux*EE*Sqrt2/(2*SW)                    |1
DDW+ |~T1  |~b2  |     |Zt11*Zb21*Maux*EE*Sqrt2/(2*SW)                    |1
DDW+ |~T2  |~b1  |     |Zt21*Zb11*Maux*EE*Sqrt2/(2*SW)                    |1
DDW+ |~T2  |~b2  |     |Zt21*Zb21*Maux*EE*Sqrt2/(2*SW)                    |1
DDW+ |~UL  |~dL  |     |Maux*EE*Sqrt2/(2*SW)                              |1
