ifeq ($(FC),)
$(error  This model needs Fortan compiler. Please install Fortan.)    
endif

include ../include/modelMakefile

specialClean: 	 
	rm -f  omega decay spectr inp nngg.out
	rm -f  lib/nngg-nm4b/lGamma.exe