
include ../include/modelMakefile

specialClean: 
	rm -f  suspect2_lha.in suspect2_lha.out suspect2.out nngg.out nngg.in  output.flh
	rm -f  LesHouches.in  Messages.out  LesHin LesHout SPheno.spc 
	rm -f tree.slha 