ifeq ($(FC),)
$(error  This model needs Fortan compiler. Please install Fortan. )    
endif

include ../include/modelMakefile

specialClean:
	rm -f micromegas.in CPsuperH.in CPsuperH.out Key.dat cpsuperh2_slha.out