#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.0 on 19-Apr-2016 22:32
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#ifdef PARALLEL
#define gzvar1s gzvar0s
#define gzvar1a gzvar0a
#define gzkinvars gzvar0a
#endif

#else

#include "decl.h"

#ifdef PARALLEL
	marker b0s(0), b0a(0), bhel(0)
	common /var0s/ b0s
	common /var0a/ b0a
	common /helvars/ bhel
#endif

	ComplexType Sub29, Sub27, Sub8, Sub23, Sub1, Sub4, Sub20
	ComplexType Sub25, Sub5, Sub3, Sub21, Sub30, Sub28, Sub24
	ComplexType Sub22, Sub7, Sub2, Sub26, Sub31, Sub32, Sub33
	ComplexType Sub19, Sub89, Sub6, Sub34, pave1(Nbb)
	ComplexType pave2(Nbb), pave3(Nbb), pave4(Nbb), pave5(Nbb)
	ComplexType pave6(Nbb), pave7(Nbb), pave8(Nbb), pave9(Nbb)
	ComplexType pave10(Ncc), pave11(Ncc), pave12(Ncc)
	ComplexType pave13(Nbb), pave14(Ncc), pave15(Ncc)
	ComplexType pave16(Nbb), pave17(Nbb), pave18(Ncc)
	ComplexType pave19(Ncc), pave20(Ncc), pave21(Ncc)
	ComplexType pave22(Ncc), pave25(Nbb), pave32(Ncc)
	ComplexType pave33(Ncc), pave34(Ncc), pave35(Ncc)
	ComplexType pave36(Ncc), pave50(Ncc), pave51(Ncc)
	common /gzvar1s/ Sub29, Sub27, Sub8, Sub23, Sub1, Sub4, Sub20
	common /gzvar1s/ Sub25, Sub5, Sub3, Sub21, Sub30, Sub28
	common /gzvar1s/ Sub24, Sub22, Sub7, Sub2, Sub26, Sub31
	common /gzvar1s/ Sub32, Sub33, Sub19, Sub89, Sub6, Sub34
	common /gzvar1s/ pave1, pave2, pave3, pave4, pave5, pave6
	common /gzvar1s/ pave7, pave8, pave9, pave10, pave11, pave12
	common /gzvar1s/ pave13, pave14, pave15, pave16, pave17
	common /gzvar1s/ pave18, pave19, pave20, pave21, pave22
	common /gzvar1s/ pave25, pave32, pave33, pave34, pave35
	common /gzvar1s/ pave36, pave50, pave51

	ComplexType pave23(Ncc), pave24(Ncc), pave26(Nbb)
	ComplexType pave27(Ncc), pave28(Ncc), pave29(Ncc)
	ComplexType pave30(Nbb), pave31(Ncc), pave37(Ncc)
	ComplexType pave38(Ncc), pave39(Ncc), pave40(Ncc)
	ComplexType pave41(Ndd), pave42(Ndd), pave43(Ndd)
	ComplexType pave44(Ndd), pave45(Ndd), pave46(Ndd)
	ComplexType pave47(Ndd), pave48(Ndd), pave49(Ndd)
	common /gzvar1a/ pave23, pave24, pave26, pave27, pave28
	common /gzvar1a/ pave29, pave30, pave31, pave37, pave38
	common /gzvar1a/ pave39, pave40, pave41, pave42, pave43
	common /gzvar1a/ pave44, pave45, pave46, pave47, pave48
	common /gzvar1a/ pave49

	ComplexType Pair4, Pair7, Pair6, Pair5, Pair3, Pair1, Pair2
	ComplexType Eps1, Abb108, Abb101, Abb105, Abb196, Abb98
	ComplexType Abb195, Abb109, Abb102, Abb197, Abb31, Abb19
	ComplexType Abb51, Abb48, Abb27, Abb82, Abb24, Abb55, Abb25
	ComplexType Abb52, Abb71, Abb70, Abb62, Abb28, Abb68, Abb20
	ComplexType Abb38, Abb44, Abb26, Abb29, Abb53, Abb50, Abb49
	ComplexType Abb110, Abb22, Abb120, Abb92, Abb112, Abb199
	ComplexType Abb114, Abb157, Abb47, Abb93, Abb111, Abb198
	ComplexType Abb94, Abb23, Abb95, Abb7, Abb177, Abb8, Abb3
	ComplexType Abb4, Abb5, Abb6, Abb10, Abb9, Abb133, Abb121
	ComplexType Abb129, Abb148, Abb123, Abb168, Abb152, Abb174
	ComplexType Abb117, Abb2, Abb15, Abb16, Abb140, Abb184
	ComplexType Abb18, Abb138, Abb17, Abb131, Abb97, Abb126
	ComplexType Abb127, Abb164, Abb96, Abb122, Abb107, Abb124
	ComplexType Abb201, Abb207, Abb139, Abb183, Abb147, Abb137
	ComplexType Abb132, Abb146, Abb154, Abb69, Abb45, Abb155
	ComplexType Abb37, Abb36, Abb41, Abb39, Abb141, Abb150
	ComplexType Abb191, Abb176, Abb67, Abb169, Abb91, Abb83
	ComplexType Abb189, Abb80, Abb81, Abb166, Abb125, Abb143
	ComplexType Abb171, Abb113, Abb151, Abb173, Abb149, Abb160
	ComplexType Abb159, Abb1, Abb11, Abb12, Abb180, Abb136
	ComplexType Abb115, Abb116, Abb206, Abb158, Abb200, Abb118
	ComplexType Abb203, Abb14, Abb182, Abb13, Abb175, Abb54
	ComplexType Abb90, Abb104, Abb162, Abb163, Abb128, Abb103
	ComplexType Abb87, Abb165, Abb100, Abb76, Abb99, Abb167
	ComplexType Abb130, Abb85, Abb57, Abb179, Abb106, Abb135
	ComplexType Abb33, Abb42, Abb46, Abb73, Abb75, Abb156, Abb21
	ComplexType Abb84, Abb142, Abb170, Abb186, Abb89, Abb79
	ComplexType Abb74, Abb35, Abb202, Abb188, Abb40, Abb88
	ComplexType Abb78, Abb77, Abb66, Abb181, Abb86, Abb64, Abb59
	ComplexType Abb178, Abb134, Abb187, Abb30, Abb204, Abb192
	ComplexType Abb194, Abb72, Abb153, Abb43, Abb119, Abb161
	ComplexType Abb185, Abb209, Abb205, Abb145, Abb172, Abb190
	ComplexType Abb144, Abb208, Abb193, Abb32, Abb56, Abb65
	ComplexType Abb61, Abb34, Abb60, Abb63, Abb58, Sub35, Sub9
	ComplexType Sub15, Sub16, Sub17, Sub18, Sub36, Sub40, Sub38
	ComplexType Sub41, Sub86, Sub39, Sub37, Sub44, Sub50, Sub87
	ComplexType Sub88, Sub11, Sub51, Sub45, Sub13, Sub10, Sub55
	ComplexType Sub54, Sub83, Sub71, Sub73, Sub82, Sub69, Sub77
	ComplexType Sub78, Sub75, Sub74, Sub70, Sub76, Sub84, Sub72
	ComplexType Sub81, Sub79, Sub80, Sub46, Sub42, Sub52, Sub48
	ComplexType Sub49, Sub53, Sub43, Sub47, Sub63, Sub57, Sub58
	ComplexType Sub60, Sub62, Sub56, Sub59, Sub61, Sub14, Sub12
	ComplexType Sub64, Sub65, Sub85, Sub67, Sub68, Sub66
	common /gzvar1h/ Pair4, Pair7, Pair6, Pair5, Pair3, Pair1
	common /gzvar1h/ Pair2, Eps1, Abb108, Abb101, Abb105, Abb196
	common /gzvar1h/ Abb98, Abb195, Abb109, Abb102, Abb197
	common /gzvar1h/ Abb31, Abb19, Abb51, Abb48, Abb27, Abb82
	common /gzvar1h/ Abb24, Abb55, Abb25, Abb52, Abb71, Abb70
	common /gzvar1h/ Abb62, Abb28, Abb68, Abb20, Abb38, Abb44
	common /gzvar1h/ Abb26, Abb29, Abb53, Abb50, Abb49, Abb110
	common /gzvar1h/ Abb22, Abb120, Abb92, Abb112, Abb199
	common /gzvar1h/ Abb114, Abb157, Abb47, Abb93, Abb111
	common /gzvar1h/ Abb198, Abb94, Abb23, Abb95, Abb7, Abb177
	common /gzvar1h/ Abb8, Abb3, Abb4, Abb5, Abb6, Abb10, Abb9
	common /gzvar1h/ Abb133, Abb121, Abb129, Abb148, Abb123
	common /gzvar1h/ Abb168, Abb152, Abb174, Abb117, Abb2, Abb15
	common /gzvar1h/ Abb16, Abb140, Abb184, Abb18, Abb138, Abb17
	common /gzvar1h/ Abb131, Abb97, Abb126, Abb127, Abb164
	common /gzvar1h/ Abb96, Abb122, Abb107, Abb124, Abb201
	common /gzvar1h/ Abb207, Abb139, Abb183, Abb147, Abb137
	common /gzvar1h/ Abb132, Abb146, Abb154, Abb69, Abb45
	common /gzvar1h/ Abb155, Abb37, Abb36, Abb41, Abb39, Abb141
	common /gzvar1h/ Abb150, Abb191, Abb176, Abb67, Abb169
	common /gzvar1h/ Abb91, Abb83, Abb189, Abb80, Abb81, Abb166
	common /gzvar1h/ Abb125, Abb143, Abb171, Abb113, Abb151
	common /gzvar1h/ Abb173, Abb149, Abb160, Abb159, Abb1, Abb11
	common /gzvar1h/ Abb12, Abb180, Abb136, Abb115, Abb116
	common /gzvar1h/ Abb206, Abb158, Abb200, Abb118, Abb203
	common /gzvar1h/ Abb14, Abb182, Abb13, Abb175, Abb54, Abb90
	common /gzvar1h/ Abb104, Abb162, Abb163, Abb128, Abb103
	common /gzvar1h/ Abb87, Abb165, Abb100, Abb76, Abb99, Abb167
	common /gzvar1h/ Abb130, Abb85, Abb57, Abb179, Abb106
	common /gzvar1h/ Abb135, Abb33, Abb42, Abb46, Abb73, Abb75
	common /gzvar1h/ Abb156, Abb21, Abb84, Abb142, Abb170
	common /gzvar1h/ Abb186, Abb89, Abb79, Abb74, Abb35, Abb202
	common /gzvar1h/ Abb188, Abb40, Abb88, Abb78, Abb77, Abb66
	common /gzvar1h/ Abb181, Abb86, Abb64, Abb59, Abb178, Abb134
	common /gzvar1h/ Abb187, Abb30, Abb204, Abb192, Abb194
	common /gzvar1h/ Abb72, Abb153, Abb43, Abb119, Abb161
	common /gzvar1h/ Abb185, Abb209, Abb205, Abb145, Abb172
	common /gzvar1h/ Abb190, Abb144, Abb208, Abb193, Abb32
	common /gzvar1h/ Abb56, Abb65, Abb61, Abb34, Abb60, Abb63
	common /gzvar1h/ Abb58, Sub35, Sub9, Sub15, Sub16, Sub17
	common /gzvar1h/ Sub18, Sub36, Sub40, Sub38, Sub41, Sub86
	common /gzvar1h/ Sub39, Sub37, Sub44, Sub50, Sub87, Sub88
	common /gzvar1h/ Sub11, Sub51, Sub45, Sub13, Sub10, Sub55
	common /gzvar1h/ Sub54, Sub83, Sub71, Sub73, Sub82, Sub69
	common /gzvar1h/ Sub77, Sub78, Sub75, Sub74, Sub70, Sub76
	common /gzvar1h/ Sub84, Sub72, Sub81, Sub79, Sub80, Sub46
	common /gzvar1h/ Sub42, Sub52, Sub48, Sub49, Sub53, Sub43
	common /gzvar1h/ Sub47, Sub63, Sub57, Sub58, Sub60, Sub62
	common /gzvar1h/ Sub56, Sub59, Sub61, Sub14, Sub12, Sub64
	common /gzvar1h/ Sub65, Sub85, Sub67, Sub68, Sub66

	RealType S, T, U
	common /gzkinvars/ S, T, U

	integer seq(2), Hel(4)
	common /gzhelvars/ seq, Hel

	ComplexType Cloop(1)
	common /gzformfactors/ Cloop

#ifdef PARALLEL
	marker e0s(0), e0a(0), ehel(0)
	common /var0s/ e0s
	common /var0a/ e0a
	common /helvars/ ehel
#endif

#endif
