#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.0 on 19-Apr-2016 22:14
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 4

#include "decl.h"

#ifdef PARALLEL
#define var1s var0s
#define var1a var0a
#define kinvars var0a
#endif

#else

#include "decl.h"

#ifdef PARALLEL
	marker b0s(0), b0a(0), bhel(0)
	common /var0s/ b0s
	common /var0a/ b0a
	common /helvars/ bhel
#endif

	ComplexType Sub2, Sub13, Sub11, Sub10, Sub3, Sub8, Sub4, Sub1
	ComplexType Sub5, Sub9, Sub12, pave1(Nbb), pave2(Nbb)
	ComplexType pave3(Nbb), pave4(Nbb), pave5(Nbb), pave6(Nbb)
	ComplexType pave7(Nbb), pave8(Nbb), pave9(Nbb), pave10(Nbb)
	ComplexType pave11(Nbb), pave12(Ncc), pave13(Ncc)
	ComplexType pave14(Ncc), pave15(Ncc), pave16(Ncc)
	ComplexType pave17(Ncc), pave18(Ncc), pave19(Ncc)
	ComplexType pave20(Ncc), pave21(Ncc), pave28(Ncc)
	ComplexType pave29(Ncc), pave30(Ncc), pave31(Ncc)
	ComplexType pave38(Ncc)
	common /var1s/ Sub2, Sub13, Sub11, Sub10, Sub3, Sub8, Sub4
	common /var1s/ Sub1, Sub5, Sub9, Sub12, pave1, pave2, pave3
	common /var1s/ pave4, pave5, pave6, pave7, pave8, pave9
	common /var1s/ pave10, pave11, pave12, pave13, pave14
	common /var1s/ pave15, pave16, pave17, pave18, pave19
	common /var1s/ pave20, pave21, pave28, pave29, pave30
	common /var1s/ pave31, pave38

	ComplexType pave22(Nbb), pave23(Nbb), pave24(Ncc)
	ComplexType pave25(Ncc), pave26(Ncc), pave27(Ncc)
	ComplexType pave32(Ndd), pave33(Ndd), pave34(Ndd)
	ComplexType pave35(Ndd), pave36(Ndd), pave37(Ndd)
	ComplexType pave39(Ndd), pave40(Ndd)
	common /var1a/ pave22, pave23, pave24, pave25, pave26, pave27
	common /var1a/ pave32, pave33, pave34, pave35, pave36
	common /var1a/ pave37, pave39, pave40

	ComplexType Pair3, Pair6, Pair4, Pair1, Pair5, Pair7, Pair2
	ComplexType Abb81, Abb6, Abb51, Abb25, Abb49, Abb10, Abb2
	ComplexType Abb34, Abb83, Abb78, Abb85, Abb166, Abb165
	ComplexType Abb164, Abb30, Abb9, Abb32, Abb1, Abb8, Abb33
	ComplexType Abb52, Abb5, Abb19, Abb29, Abb63, Abb43, Abb12
	ComplexType Abb36, Abb7, Abb31, Abb96, Abb88, Abb72, Abb168
	ComplexType Abb87, Abb130, Abb90, Abb73, Abb86, Abb167
	ComplexType Abb74, Abb28, Abb4, Abb75, Abb97, Abb123, Abb94
	ComplexType Abb93, Abb111, Abb153, Abb113, Abb128, Abb77
	ComplexType Abb84, Abb107, Abb101, Abb102, Abb137, Abb98
	ComplexType Abb99, Abb139, Abb122, Abb76, Abb171, Abb175
	ComplexType Abb110, Abb152, Abb112, Abb108, Abb18, Abb20
	ComplexType Abb22, Abb13, Abb26, Abb71, Abb64, Abb67, Abb62
	ComplexType Abb117, Abb118, Abb143, Abb144, Abb158, Abb89
	ComplexType Abb119, Abb120, Abb116, Abb124, Abb155, Abb156
	ComplexType Abb133, Abb132, Abb149, Abb115, Abb92, Abb131
	ComplexType Abb174, Abb170, Abb91, Abb127, Abb125, Abb151
	ComplexType Abb162, Abb160, Abb163, Abb35, Abb82, Abb80
	ComplexType Abb142, Abb135, Abb136, Abb138, Abb104, Abb100
	ComplexType Abb103, Abb157, Abb56, Abb169, Abb79, Abb61
	ComplexType Abb68, Abb66, Abb148, Abb60, Abb70, Abb114
	ComplexType Abb105, Abb106, Abb140, Abb141, Abb129, Abb3
	ComplexType Abb57, Abb55, Abb65, Abb27, Abb53, Abb54, Abb154
	ComplexType Abb159, Abb58, Abb14, Abb23, Abb21, Abb16
	ComplexType Abb150, Abb146, Abb47, Abb59, Abb69, Abb38
	ComplexType Abb147, Abb45, Abb40, Abb109, Abb48, Abb11
	ComplexType Abb172, Abb50, Abb24, Abb95, Abb134, Abb121
	ComplexType Abb145, Abb173, Abb177, Abb176, Abb42, Abb37
	ComplexType Abb46, Abb39, Abb126, Abb17, Abb44, Abb15, Abb41
	ComplexType Abb161, Sub50, Sub14, Sub54, Sub59, Sub53, Sub15
	ComplexType Sub29, Sub32, Sub28, Sub31, Sub46, Sub26, Sub52
	ComplexType Sub51, Sub55, Sub48, Sub27, Sub49, Sub56, Sub18
	ComplexType Sub21, Sub23, Sub25, Sub7, Sub17, Sub24, Sub22
	ComplexType Sub20, Sub6, Sub36, Sub38, Sub40, Sub45, Sub34
	ComplexType Sub42, Sub39, Sub41, Sub35, Sub37, Sub44, Sub43
	ComplexType Sub16, Sub19, Sub30, Sub33, Sub47, Sub58, Sub57
	ComplexType Sub60
	common /var1h/ Pair3, Pair6, Pair4, Pair1, Pair5, Pair7
	common /var1h/ Pair2, Abb81, Abb6, Abb51, Abb25, Abb49
	common /var1h/ Abb10, Abb2, Abb34, Abb83, Abb78, Abb85
	common /var1h/ Abb166, Abb165, Abb164, Abb30, Abb9, Abb32
	common /var1h/ Abb1, Abb8, Abb33, Abb52, Abb5, Abb19, Abb29
	common /var1h/ Abb63, Abb43, Abb12, Abb36, Abb7, Abb31
	common /var1h/ Abb96, Abb88, Abb72, Abb168, Abb87, Abb130
	common /var1h/ Abb90, Abb73, Abb86, Abb167, Abb74, Abb28
	common /var1h/ Abb4, Abb75, Abb97, Abb123, Abb94, Abb93
	common /var1h/ Abb111, Abb153, Abb113, Abb128, Abb77, Abb84
	common /var1h/ Abb107, Abb101, Abb102, Abb137, Abb98, Abb99
	common /var1h/ Abb139, Abb122, Abb76, Abb171, Abb175, Abb110
	common /var1h/ Abb152, Abb112, Abb108, Abb18, Abb20, Abb22
	common /var1h/ Abb13, Abb26, Abb71, Abb64, Abb67, Abb62
	common /var1h/ Abb117, Abb118, Abb143, Abb144, Abb158, Abb89
	common /var1h/ Abb119, Abb120, Abb116, Abb124, Abb155
	common /var1h/ Abb156, Abb133, Abb132, Abb149, Abb115, Abb92
	common /var1h/ Abb131, Abb174, Abb170, Abb91, Abb127, Abb125
	common /var1h/ Abb151, Abb162, Abb160, Abb163, Abb35, Abb82
	common /var1h/ Abb80, Abb142, Abb135, Abb136, Abb138, Abb104
	common /var1h/ Abb100, Abb103, Abb157, Abb56, Abb169, Abb79
	common /var1h/ Abb61, Abb68, Abb66, Abb148, Abb60, Abb70
	common /var1h/ Abb114, Abb105, Abb106, Abb140, Abb141
	common /var1h/ Abb129, Abb3, Abb57, Abb55, Abb65, Abb27
	common /var1h/ Abb53, Abb54, Abb154, Abb159, Abb58, Abb14
	common /var1h/ Abb23, Abb21, Abb16, Abb150, Abb146, Abb47
	common /var1h/ Abb59, Abb69, Abb38, Abb147, Abb45, Abb40
	common /var1h/ Abb109, Abb48, Abb11, Abb172, Abb50, Abb24
	common /var1h/ Abb95, Abb134, Abb121, Abb145, Abb173, Abb177
	common /var1h/ Abb176, Abb42, Abb37, Abb46, Abb39, Abb126
	common /var1h/ Abb17, Abb44, Abb15, Abb41, Abb161, Sub50
	common /var1h/ Sub14, Sub54, Sub59, Sub53, Sub15, Sub29
	common /var1h/ Sub32, Sub28, Sub31, Sub46, Sub26, Sub52
	common /var1h/ Sub51, Sub55, Sub48, Sub27, Sub49, Sub56
	common /var1h/ Sub18, Sub21, Sub23, Sub25, Sub7, Sub17
	common /var1h/ Sub24, Sub22, Sub20, Sub6, Sub36, Sub38
	common /var1h/ Sub40, Sub45, Sub34, Sub42, Sub39, Sub41
	common /var1h/ Sub35, Sub37, Sub44, Sub43, Sub16, Sub19
	common /var1h/ Sub30, Sub33, Sub47, Sub58, Sub57, Sub60

	RealType S, T, U
	common /kinvars/ S, T, U

	integer seq(2), Hel(4)
	common /helvars/ seq, Hel

	ComplexType Cloop(1)
	common /formfactors/ Cloop

#ifdef PARALLEL
	marker e0s(0), e0a(0), ehel(0)
	common /var0s/ e0s
	common /var0a/ e0a
	common /helvars/ ehel
#endif

#endif
