* gzvars.h
* variable declarations
* generated by FormCalc 25 Oct 2014 23:26

#include "decl.h"

	double precision S, T, U
	common /gzkinvars/ S, T, U

	integer Hel(4)
	common /gzkinvars/ Hel

	double complex F3, F6, F35, F37, F49, F38, F40, F41, F109
	double complex F169, F112, F111, F173, F116, F36, F39, Pair4
	double complex Pair8, Pair11, Pair9, Pair10, Eps12, Eps13
	double complex Abb14, Abb15, Abb87, Abb88, Abb89, Abb90, Abb22
	double complex Abb23, Abb170, Abb174, Abb42, Abb50, Abb113
	double complex Abb117, Abb43, Abb51, Abb16, Abb63, Abb64
	double complex Abb24, Abb5, Abb44, Abb52, Abb7, Abb137, Abb139
	double complex Abb53, Abb45, Abb17, Abb65, Abb66, Abb25
	double complex Abb187, Abb190, Abb46, Abb47, Abb18, Abb67
	double complex Abb68, Abb26, Abb19, Abb69, Abb70, Abb27
	double complex AbbSum199, AbbSum203, AbbSum1049, AbbSum1051
	double complex AbbSum240, AbbSum265, AbbSum1031, AbbSum1033
	double complex AbbSum292, AbbSum238, AbbSum419, AbbSum228
	double complex AbbSum421, AbbSum429, AbbSum425, AbbSum1043
	double complex AbbSum1035, AbbSum254, AbbSum264, AbbSum412
	double complex AbbSum219, AbbSum1039, AbbSum1053, AbbSum1045
	double complex AbbSum436, AbbSum319, AbbSum409, AbbSum488
	double complex AbbSum171, AbbSum259, AbbSum456, AbbSum239
	double complex AbbSum261, AbbSum175, AbbSum501, AbbSum471
	double complex AbbSum468, AbbSum492, AbbSum657, AbbSum886
	double complex AbbSum864, AbbSum866, AbbSum742, AbbSum740
	double complex AbbSum748, AbbSum744, AbbSum462, AbbSum114
	double complex AbbSum848, AbbSum301, AbbSum812, AbbSum836
	double complex AbbSum834, AbbSum760, AbbSum810, AbbSum844
	double complex AbbSum860, AbbSum880, AbbSum1065, AbbSum1067
	double complex AbbSum856, AbbSum1241, AbbSum1299, AbbSum381
	double complex AbbSum694, AbbSum651, AbbSum453, AbbSum1005
	double complex AbbSum777, AbbSum842, AbbSum858, AbbSum1253
	double complex AbbSum1080, AbbSum188, AbbSum1063, AbbSum1214
	double complex AbbSum211, AbbSum1239, AbbSum1287, AbbSum282
	double complex AbbSum1029, AbbSum274, AbbSum283, AbbSum1023
	double complex AbbSum286, AbbSum1082, AbbSum217, AbbSum209
	double complex AbbSum726, AbbSum884, AbbSum682, AbbSum664
	double complex AbbSum708, AbbSum670, AbbSum30, AbbSum196
	double complex AbbSum20, AbbSum21, AbbSum1059, AbbSum498
	double complex AbbSum878, AbbSum1001, AbbSum1078, AbbSum1086
	double complex AbbSum1074, AbbSum715, AbbSum656, AbbSum485
	double complex AbbSum1225, AbbSum1275, AbbSum384, AbbSum780
	double complex AbbSum327, AbbSum346, AbbSum1227, AbbSum1055
	double complex AbbSum343, AbbSum433, AbbSum1216, AbbSum479
	double complex AbbSum544, AbbSum1277, AbbSum764, AbbSum872
	double complex AbbSum1291, AbbSum1219, AbbSum919, AbbSum1218
	double complex AbbSum198, AbbSum1193, AbbSum920, AbbSum1081
	double complex AbbSum191, AbbSum1064, AbbSum1215, AbbSum212
	double complex AbbSum921, AbbSum1205, AbbSum78, AbbSum296
	double complex AbbSum590, AbbSum415, AbbSum304, AbbSum627
	double complex AbbSum814, AbbSum818, AbbSum838, AbbSum1184
	double complex AbbSum643, AbbSum989, AbbSum1096, AbbSum1050
	double complex AbbSum1052, AbbSum647, AbbSum1037, AbbSum1054
	double complex AbbSum1047, AbbSum1183, AbbSum1177, AbbSum1185
	double complex AbbSum581, AbbSum1034, AbbSum334, AbbSum1032
	double complex AbbSum268, AbbSum556, AbbSum251, AbbSum1022
	double complex AbbSum389, AbbSum376, AbbSum313, AbbSum1245
	double complex AbbSum591, AbbSum235, AbbSum1126, AbbSum297
	double complex AbbSum300, AbbSum403, AbbSum416, AbbSum250
	double complex AbbSum1021, AbbSum557, AbbSum580, AbbSum1149
	double complex AbbSum525, AbbSum635, AbbSum349, AbbSum294
	double complex AbbSum362, AbbSum248, AbbSum269, AbbSum278
	double complex AbbSum262, AbbSum438, AbbSum321, AbbSum459
	double complex AbbSum1114, AbbSum382, AbbSum1256, AbbSum295
	double complex AbbSum279, AbbSum414, AbbSum410, AbbSum247
	double complex AbbSum420, AbbSum232, AbbSum424, AbbSum1154
	double complex AbbSum560, AbbSum224, AbbSum588, AbbSum430
	double complex AbbSum428, AbbSum1044, AbbSum1042, AbbSum491
	double complex AbbSum641, AbbSum361, AbbSum293, AbbSum242
	double complex AbbSum350, AbbSum1148, AbbSum644, AbbSum1295
	double complex AbbSum839, AbbSum1168, AbbSum1173, AbbSum964
	double complex AbbSum734, AbbSum1229, AbbSum819, AbbSum504
	double complex AbbSum474, AbbSum470, AbbSum617, AbbSum938
	double complex AbbSum738, AbbSum1140, AbbSum754, AbbSum1003
	double complex AbbSum995, AbbSum935, AbbSum828, AbbSum732
	double complex AbbSum730, AbbSum1144, AbbSum805, AbbSum815
	double complex AbbSum574, AbbSum288, AbbSum305, AbbSum298
	double complex AbbSum628, AbbSum615, AbbSum788, AbbSum769
	double complex AbbSum792, AbbSum495, AbbSum661, AbbSum653
	double complex AbbSum455, AbbSum937, AbbSum913, AbbSum1230
	double complex AbbSum887, AbbSum865, AbbSum697, AbbSum867
	double complex AbbSum1172, AbbSum1167, AbbSum1266, AbbSum1296
	double complex AbbSum901, AbbSum980, AbbSum625, AbbSum837
	double complex AbbSum835, AbbSum761, AbbSum1171, AbbSum1069
	double complex AbbSum1300, AbbSum1006, AbbSum1288, AbbSum743
	double complex AbbSum741, AbbSum813, AbbSum811, AbbSum1176
	double complex AbbSum1165, AbbSum749, AbbSum746, AbbSum465
	double complex AbbSum118, AbbSum845, AbbSum861, AbbSum881
	double complex AbbSum943, AbbSum1066, AbbSum857, AbbSum1242
	double complex AbbSum843, AbbSum859, AbbSum1240, AbbSum849
	double complex AbbSum987, AbbSum1158, AbbSum1280, AbbSum303
	double complex AbbSum779, AbbSum974, AbbSum990, AbbSum549
	double complex AbbSum618, AbbSum693, AbbSum947, AbbSum684
	double complex AbbSum914, AbbSum594, AbbSum714, AbbSum206
	double complex AbbSum1018, AbbSum770, AbbSum793, AbbSum1128
	double complex AbbSum668, AbbSum1267, AbbSum678, AbbSum924
	double complex AbbSum956, AbbSum561, AbbSum606, AbbSum299
	double complex AbbSum1013, AbbSum314, AbbSum1004, AbbSum996
	double complex AbbSum1198, AbbSum1246, AbbSum302, AbbSum404
	double complex AbbSum1014, AbbSum1141, AbbSum616, AbbSum936
	double complex AbbSum1145, AbbSum704, AbbSum707, AbbSum72
	double complex AbbSum663, AbbSum709, AbbSum739, AbbSum731
	double complex AbbSum755, AbbSum806, AbbSum733, AbbSum789
	double complex AbbSum829, AbbSum562, AbbSum607, AbbSum955
	double complex AbbSum925, AbbSum679, AbbSum377, AbbSum1127
	double complex AbbSum669, AbbSum713, AbbSum205, AbbSum289
	double complex AbbSum1017, AbbSum575, AbbSum948, AbbSum595
	double complex AbbSum683, AbbSum735, AbbSum390, AbbSum1223
	double complex AbbSum692, AbbSum335, AbbSum1261, AbbSum1211
	double complex AbbSum728, AbbSum387, AbbSum782, AbbSum1002
	double complex AbbSum386, AbbSum328, AbbSum356, AbbSum284
	double complex AbbSum276, AbbSum388, AbbSum285, AbbSum1028
	double complex AbbSum355, AbbSum348, AbbSum287, AbbSum1085
	double complex AbbSum218, AbbSum214, AbbSum1079, AbbSum1089
	double complex AbbSum1077, AbbSum1226, AbbSum1228, AbbSum435
	double complex AbbSum1217, AbbSum1058, AbbSum1104, AbbSum1178
	double complex AbbSum482, AbbSum532, AbbSum344, AbbSum1115
	double complex AbbSum1124, AbbSum554, AbbSum1278, AbbSum1281
	double complex AbbSum1159, AbbSum727, AbbSum729, AbbSum783
	double complex AbbSum765, AbbSum879, AbbSum885, AbbSum1276
	double complex AbbSum781, AbbSum691, AbbSum917, AbbSum604
	double complex AbbSum954, AbbSum614, AbbSum573, AbbSum666
	double complex AbbSum1139, AbbSum712, AbbSum720, AbbSum674
	double complex AbbSum31, AbbSum201, AbbSum33, AbbSum875
	double complex AbbSum28, AbbSum29, AbbSum1060, AbbSum963
	double complex AbbSum934, AbbSum907, AbbSum487, AbbSum500
	double complex AbbSum660, AbbSum1294, AbbSum1030, AbbSum1262
	double complex AbbSum1097, AbbSum965, AbbSum526, AbbSum636
	double complex AbbSum902, AbbSum981, AbbSum507, AbbSum970
	double complex AbbSum323, AbbSum622, AbbSum365, AbbSum975
	double complex AbbSum156, AbbSum630, AbbSum266, AbbSum439
	double complex AbbSum850, AbbSum722, AbbSum752, AbbSum1068
	double complex AbbSum972, AbbSum398, AbbSum801, AbbSum273
	double complex AbbSum55, AbbSum104, AbbSum846, AbbSum437
	double complex AbbSum603, AbbSum271, AbbSum185, AbbSum476
	double complex AbbSum510, AbbSum1191, AbbSum441, AbbSum440
	double complex AbbSum853, AbbSum1213, AbbSum877, AbbSum181
	double complex AbbSum434, AbbSum851, AbbSum442, AbbSum847
	double complex AbbSum991, AbbSum645, AbbSum490, AbbSum503
	double complex AbbSum992, AbbSum962, AbbSum514, AbbSum640
	double complex AbbSum508, AbbSum497, AbbSum623, AbbSum506
	double complex AbbSum973, AbbSum889, AbbSum646, AbbSum399
	double complex AbbSum723, AbbSum725, AbbSum602, AbbSum551
	double complex AbbSum612, AbbSum530, AbbSum601, AbbSum324
	double complex AbbSum648, AbbSum458, AbbSum77, AbbSum478
	double complex AbbSum613, AbbSum341, AbbSum986, AbbSum473
	double complex AbbSum893, AbbSum624, AbbSum971, AbbSum833
	double complex AbbSum370, AbbSum906, AbbSum467, AbbSum953
	double complex AbbSum961, AbbSum816, AbbSum976, AbbSum417
	double complex AbbSum1186, AbbSum1012, AbbSum227, AbbSum183
	double complex AbbSum484, AbbSum1093, AbbSum446, AbbSum753
	double complex AbbSum1286, AbbSum1156, AbbSum662, AbbSum667
	double complex AbbSum520, AbbSum157, AbbSum159, AbbSum418
	double complex AbbSum898, AbbSum1187, AbbSum432, AbbSum427
	double complex AbbSum869, AbbSum587, AbbSum817, AbbSum632
	double complex AbbSum852, AbbSum868, AbbSum105, AbbSum908
	double complex AbbSum905, AbbSum862, AbbSum984, AbbSum1208
	double complex AbbSum1283, AbbSum873, AbbSum79, AbbSum1166
	double complex AbbSum876, AbbSum97, AbbSum92, AbbSum180
	double complex AbbSum724, AbbSum1155, AbbSum874, AbbSum61
	double complex AbbSum918, AbbSum463, AbbSum452, AbbSum600
	double complex AbbSum99, AbbSum968, AbbSum608, AbbSum486
	double complex AbbSum619, AbbSum391, AbbSum621, AbbSum1125
	double complex AbbSum555, AbbSum512, AbbSum969, AbbSum960
	double complex AbbSum496, AbbSum658, AbbSum1263, AbbSum951
	double complex AbbSum489, AbbSum502, AbbSum499, AbbSum685
	double complex AbbSum480, AbbSum1264, AbbSum597, AbbSum966
	double complex AbbSum620, AbbSum609, AbbSum598, AbbSum605
	double complex AbbSum599, AbbSum639, AbbSum529, AbbSum493
	double complex AbbSum638, AbbSum528, AbbSum533, AbbSum949
	double complex AbbSum270, AbbSum392, AbbSum73, AbbSum337
	double complex AbbSum665, AbbSum959, AbbSum626, AbbSum610
	double complex AbbSum454, AbbSum74, AbbSum95, AbbSum637
	double complex AbbSum505, AbbSum888, AbbSum548, AbbSum527
	double complex AbbSum477, AbbSum982, AbbSum903, AbbSum494
	double complex AbbSum882, AbbSum103, AbbSum596, AbbSum481
	double complex AbbSum184, AbbSum950, AbbSum100, AbbSum883
	double complex AbbSum967, AbbSum958, AbbSum98, AbbSum93
	double complex AbbSum796, AbbSum611, AbbSum830, AbbSum466
	double complex AbbSum589, AbbSum457, AbbSum472, AbbSum469
	double complex AbbSum96, AbbSum892, AbbSum519, AbbSum957
	double complex AbbSum784, AbbSum642, AbbSum475, AbbSum509
	double complex AbbSum395, AbbSum1010, AbbSum223, AbbSum431
	double complex AbbSum451, AbbSum1024, AbbSum721, AbbSum1025
	double complex AbbSum352, AbbSum1026, AbbSum243, AbbSum1007
	double complex AbbSum1027, AbbSum353, AbbSum272, AbbSum158
	double complex AbbSum785, AbbSum267, AbbSum791, AbbSum396
	double complex AbbSum1016, AbbSum86, AbbSum56, AbbSum94
	double complex AbbSum1015, AbbSum422, AbbSum1011, AbbSum426
	double complex AbbSum231, AbbSum245, AbbSum423, AbbSum690
	double complex AbbSum102, AbbSum1190, AbbSum182, AbbSum863
	double complex AbbSum904, AbbSum62, AbbSum983, AbbSum101
	double complex AbbSum483, AbbSum107, AbbSum1092, AbbSum445
	double complex AbbSum464, AbbSum106, AbbSum585, AbbSum988
	double complex AbbSum790, AbbSum897, AbbSum281, AbbSum372
	double complex AbbSum249, AbbSum237, AbbSum280, AbbSum368
	double complex AbbSum246, AbbSum236, AbbSum400, AbbSum1147
	double complex AbbSum747, AbbSum825, AbbSum1238, AbbSum1000
	double complex AbbSum923, AbbSum291, AbbSum577, AbbSum397
	double complex AbbSum1146, AbbSum745, AbbSum823, AbbSum1235
	double complex AbbSum999, AbbSum922, AbbSum290, AbbSum576
	double complex AbbSum360, AbbSum277, AbbSum195, AbbSum216
	double complex AbbSum204, AbbSum803, AbbSum737, AbbSum933
	double complex AbbSum998, AbbSum1020, AbbSum681, AbbSum208
	double complex AbbSum706, AbbSum193, AbbSum1143, AbbSum1138
	double complex AbbSum572, AbbSum449, AbbSum460, AbbSum443
	double complex AbbSum870, AbbSum34, AbbSum871, AbbSum444
	double complex AbbSum461, AbbSum450, AbbSum32, AbbSum359
	double complex AbbSum275, AbbSum194, AbbSum213, AbbSum200
	double complex AbbSum799, AbbSum736, AbbSum930, AbbSum997
	double complex AbbSum1019, AbbSum680, AbbSum207, AbbSum705
	double complex AbbSum192, AbbSum1142, AbbSum1135, AbbSum568
	double complex AbbSum75, AbbSum71, AbbSum76, AbbSum91
	double complex AbbSum1257, AbbSum1289, AbbSum447, AbbSum629
	double complex AbbSum1251, AbbSum854, AbbSum132, AbbSum521
	double complex AbbSum540, AbbSum826, AbbSum633, AbbSum345
	double complex AbbSum522, AbbSum776, AbbSum411, AbbSum383
	double complex AbbSum890, AbbSum513, AbbSum985, AbbSum339
	double complex AbbSum899, AbbSum977, AbbSum774, AbbSum946
	double complex AbbSum1132, AbbSum809, AbbSum1113, AbbSum1259
	double complex AbbSum1290, AbbSum686, AbbSum331, AbbSum687
	double complex AbbSum448, AbbSum787, AbbSum1121, AbbSum1112
	double complex AbbSum1102, AbbSum891, AbbSum631, AbbSum592
	double complex AbbSum552, AbbSum579, AbbSum945, AbbSum307
	double complex AbbSum1110, AbbSum380, AbbSum855, AbbSum1101
	double complex AbbSum1122, AbbSum1119, AbbSum1120, AbbSum688
	double complex AbbSum1163, AbbSum134, AbbSum827, AbbSum1204
	double complex AbbSum154, AbbSum689, AbbSum952, AbbSum1197
	double complex AbbSum634, AbbSum511, AbbSum538, AbbSum515
	double complex AbbSum1133, AbbSum1272, AbbSum347, AbbSum578
	double complex AbbSum524, AbbSum1285, AbbSum778, AbbSum786
	double complex AbbSum537, AbbSum531, AbbSum768, AbbSum253
	double complex AbbSum413, AbbSum804, AbbSum539, AbbSum177
	double complex AbbSum912, AbbSum393, AbbSum333, AbbSum523
	double complex AbbSum385, AbbSum401, AbbSum373, AbbSum329
	double complex AbbSum311, AbbSum375, AbbSum160, AbbSum1244
	double complex AbbSum541, AbbSum1265, AbbSum553, AbbSum542
	double complex AbbSum979, AbbSum543, AbbSum944, AbbSum1094
	double complex AbbSum516, AbbSum1192, AbbSum176, AbbSum312
	double complex AbbSum153, AbbSum1210, AbbSum593, AbbSum894
	double complex AbbSum1108, AbbSum534, AbbSum252, AbbSum374
	double complex AbbSum1243, AbbSum1095, AbbSum909, AbbSum1252
	double complex AbbSum1157, AbbSum1279, AbbSum402, AbbSum900
	double complex AbbSum394, AbbSum978, AbbSum1109, AbbSum1090
	double complex AbbSum535, AbbSum929, AbbSum1258, AbbSum1200
	double complex AbbSum330, AbbSum1254, AbbSum654, AbbSum1292
	double complex AbbSum186, AbbSum363, AbbSum1188, AbbSum910
	double complex AbbSum1130, AbbSum306, AbbSum320, AbbSum197
	double complex AbbSum1162, AbbSum161, AbbSum1195, AbbSum915
	double complex AbbSum1234, AbbSum766, AbbSum178, AbbSum241
	double complex AbbSum795, AbbSum220, AbbSum221, AbbSum993
	double complex AbbSum696, AbbSum115, AbbSum128, AbbSum126
	double complex AbbSum108, AbbSum124, AbbSum1206, AbbSum1231
	double complex AbbSum130, AbbSum120, AbbSum122, AbbSum1070
	double complex AbbSum1169, AbbSum1174, AbbSum1233, AbbSum255
	double complex AbbSum165, AbbSum163, AbbSum821, AbbSum840
	double complex AbbSum1072, AbbSum1087, AbbSum820, AbbSum717
	double complex AbbSum325, AbbSum649, AbbSum316, AbbSum1008
	double complex AbbSum517, AbbSum700, AbbSum701, AbbSum229
	double complex AbbSum1106, AbbSum230, AbbSum309, AbbSum364
	double complex AbbSum167, AbbSum797, AbbSum794, AbbSum558
	double complex AbbSum1150, AbbSum1131, AbbSum582, AbbSum939
	double complex AbbSum1297, AbbSum1207, AbbSum673, AbbSum772
	double complex AbbSum566, AbbSum1083, AbbSum1247, AbbSum567
	double complex AbbSum940, AbbSum927, AbbSum1151, AbbSum545
	double complex AbbSum1270, AbbSum1221, AbbSum1220, AbbSum1269
	double complex AbbSum564, AbbSum547, AbbSum926, AbbSum583
	double complex AbbSum1129, AbbSum672, AbbSum1268, AbbSum407
	double complex AbbSum210, AbbSum758, AbbSum136, AbbSum762
	double complex AbbSum1036, AbbSum1046, AbbSum258, AbbSum895
	double complex AbbSum357, AbbSum148, AbbSum146, AbbSum340
	double complex AbbSum366, AbbSum695, AbbSum671, AbbSum133
	double complex AbbSum750, AbbSum351, AbbSum144, AbbSum150
	double complex AbbSum140, AbbSum257, AbbSum142, AbbSum1117
	double complex AbbSum710, AbbSum1179, AbbSum1098, AbbSum563
	double complex AbbSum1116, AbbSum1202, AbbSum1111, AbbSum941
	double complex AbbSum916, AbbSum559, AbbSum1091, AbbSum1232
	double complex AbbSum536, AbbSum1260, AbbSum1201, AbbSum189
	double complex AbbSum655, AbbSum332, AbbSum1298, AbbSum1293
	double complex AbbSum1255, AbbSum798, AbbSum367, AbbSum1189
	double complex AbbSum911, AbbSum162, AbbSum322, AbbSum202
	double complex AbbSum1137, AbbSum1164, AbbSum308, AbbSum1209
	double complex AbbSum584, AbbSum315, AbbSum336, AbbSum59
	double complex AbbSum60, AbbSum1199, AbbSum767, AbbSum179
	double complex AbbSum1237, AbbSum1105, AbbSum226, AbbSum225
	double complex AbbSum994, AbbSum263, AbbSum1009, AbbSum310
	double complex AbbSum172, AbbSum1153, AbbSum119, AbbSum164
	double complex AbbSum326, AbbSum129, AbbSum127, AbbSum518
	double complex AbbSum699, AbbSum166, AbbSum369, AbbSum802
	double complex AbbSum110, AbbSum824, AbbSum650, AbbSum800
	double complex AbbSum318, AbbSum702, AbbSum703, AbbSum233
	double complex AbbSum125, AbbSum841, AbbSum1107, AbbSum234
	double complex AbbSum1212, AbbSum1236, AbbSum131, AbbSum121
	double complex AbbSum586, AbbSum123, AbbSum546, AbbSum1134
	double complex AbbSum405, AbbSum378, AbbSum1181, AbbSum832
	double complex AbbSum1100, AbbSum757, AbbSum1061, AbbSum57
	double complex AbbSum48, AbbSum1057, AbbSum152, AbbSum82
	double complex AbbSum1075, AbbSum659, AbbSum1056, AbbSum652
	double complex AbbSum80, AbbSum81, AbbSum831, AbbSum756
	double complex AbbSum1160, AbbSum1180, AbbSum1099, AbbSum807
	double complex AbbSum771, AbbSum571, AbbSum677, AbbSum570
	double complex AbbSum775, AbbSum1250, AbbSum358, AbbSum1161
	double complex AbbSum808, AbbSum773, AbbSum942, AbbSum932
	double complex AbbSum1170, AbbSum1152, AbbSum1175, AbbSum1224
	double complex AbbSum1274, AbbSum1248, AbbSum550, AbbSum569
	double complex AbbSum931, AbbSum822, AbbSum1271, AbbSum1282
	double complex AbbSum256, AbbSum215, AbbSum408, AbbSum1222
	double complex AbbSum759, AbbSum1136, AbbSum676, AbbSum1071
	double complex AbbSum1273, AbbSum260, AbbSum1084, AbbSum1073
	double complex AbbSum1088, AbbSum719, AbbSum716, AbbSum718
	double complex AbbSum85, AbbSum83, AbbSum54, AbbSum84
	double complex AbbSum1196, AbbSum138, AbbSum149, AbbSum147
	double complex AbbSum342, AbbSum135, AbbSum354, AbbSum145
	double complex AbbSum151, AbbSum141, AbbSum143, AbbSum896
	double complex AbbSum763, AbbSum751, AbbSum698, AbbSum1038
	double complex AbbSum371, AbbSum675, AbbSum1048, AbbSum1194
	double complex AbbSum1062, AbbSum168, AbbSum58, AbbSum1076
	double complex AbbSum1041, AbbSum155, AbbSum1040, AbbSum222
	double complex AbbSum1182, AbbSum1103, AbbSum244, AbbSum711
	double complex AbbSum379, AbbSum406, AbbSum338, AbbSum317
	double complex AbbSum928, AbbSum1123, AbbSum565, AbbSum1284
	double complex AbbSum1203, AbbSum1118, AbbSum1249
	common /gzabbrev/ F3, F6, F35, F37, F49, F38, F40, F41, F109
	common /gzabbrev/ F169, F112, F111, F173, F116, F36, F39
	common /gzabbrev/ Pair4, Pair8, Pair11, Pair9, Pair10, Eps12
	common /gzabbrev/ Eps13, Abb14, Abb15, Abb87, Abb88, Abb89
	common /gzabbrev/ Abb90, Abb22, Abb23, Abb170, Abb174, Abb42
	common /gzabbrev/ Abb50, Abb113, Abb117, Abb43, Abb51, Abb16
	common /gzabbrev/ Abb63, Abb64, Abb24, Abb5, Abb44, Abb52
	common /gzabbrev/ Abb7, Abb137, Abb139, Abb53, Abb45, Abb17
	common /gzabbrev/ Abb65, Abb66, Abb25, Abb187, Abb190, Abb46
	common /gzabbrev/ Abb47, Abb18, Abb67, Abb68, Abb26, Abb19
	common /gzabbrev/ Abb69, Abb70, Abb27, AbbSum199, AbbSum203
	common /gzabbrev/ AbbSum1049, AbbSum1051, AbbSum240, AbbSum265
	common /gzabbrev/ AbbSum1031, AbbSum1033, AbbSum292, AbbSum238
	common /gzabbrev/ AbbSum419, AbbSum228, AbbSum421, AbbSum429
	common /gzabbrev/ AbbSum425, AbbSum1043, AbbSum1035, AbbSum254
	common /gzabbrev/ AbbSum264, AbbSum412, AbbSum219, AbbSum1039
	common /gzabbrev/ AbbSum1053, AbbSum1045, AbbSum436, AbbSum319
	common /gzabbrev/ AbbSum409, AbbSum488, AbbSum171, AbbSum259
	common /gzabbrev/ AbbSum456, AbbSum239, AbbSum261, AbbSum175
	common /gzabbrev/ AbbSum501, AbbSum471, AbbSum468, AbbSum492
	common /gzabbrev/ AbbSum657, AbbSum886, AbbSum864, AbbSum866
	common /gzabbrev/ AbbSum742, AbbSum740, AbbSum748, AbbSum744
	common /gzabbrev/ AbbSum462, AbbSum114, AbbSum848, AbbSum301
	common /gzabbrev/ AbbSum812, AbbSum836, AbbSum834, AbbSum760
	common /gzabbrev/ AbbSum810, AbbSum844, AbbSum860, AbbSum880
	common /gzabbrev/ AbbSum1065, AbbSum1067, AbbSum856
	common /gzabbrev/ AbbSum1241, AbbSum1299, AbbSum381, AbbSum694
	common /gzabbrev/ AbbSum651, AbbSum453, AbbSum1005, AbbSum777
	common /gzabbrev/ AbbSum842, AbbSum858, AbbSum1253, AbbSum1080
	common /gzabbrev/ AbbSum188, AbbSum1063, AbbSum1214, AbbSum211
	common /gzabbrev/ AbbSum1239, AbbSum1287, AbbSum282
	common /gzabbrev/ AbbSum1029, AbbSum274, AbbSum283, AbbSum1023
	common /gzabbrev/ AbbSum286, AbbSum1082, AbbSum217, AbbSum209
	common /gzabbrev/ AbbSum726, AbbSum884, AbbSum682, AbbSum664
	common /gzabbrev/ AbbSum708, AbbSum670, AbbSum30, AbbSum196
	common /gzabbrev/ AbbSum20, AbbSum21, AbbSum1059, AbbSum498
	common /gzabbrev/ AbbSum878, AbbSum1001, AbbSum1078
	common /gzabbrev/ AbbSum1086, AbbSum1074, AbbSum715, AbbSum656
	common /gzabbrev/ AbbSum485, AbbSum1225, AbbSum1275, AbbSum384
	common /gzabbrev/ AbbSum780, AbbSum327, AbbSum346, AbbSum1227
	common /gzabbrev/ AbbSum1055, AbbSum343, AbbSum433, AbbSum1216
	common /gzabbrev/ AbbSum479, AbbSum544, AbbSum1277, AbbSum764
	common /gzabbrev/ AbbSum872, AbbSum1291, AbbSum1219, AbbSum919
	common /gzabbrev/ AbbSum1218, AbbSum198, AbbSum1193, AbbSum920
	common /gzabbrev/ AbbSum1081, AbbSum191, AbbSum1064
	common /gzabbrev/ AbbSum1215, AbbSum212, AbbSum921, AbbSum1205
	common /gzabbrev/ AbbSum78, AbbSum296, AbbSum590, AbbSum415
	common /gzabbrev/ AbbSum304, AbbSum627, AbbSum814, AbbSum818
	common /gzabbrev/ AbbSum838, AbbSum1184, AbbSum643, AbbSum989
	common /gzabbrev/ AbbSum1096, AbbSum1050, AbbSum1052
	common /gzabbrev/ AbbSum647, AbbSum1037, AbbSum1054
	common /gzabbrev/ AbbSum1047, AbbSum1183, AbbSum1177
	common /gzabbrev/ AbbSum1185, AbbSum581, AbbSum1034, AbbSum334
	common /gzabbrev/ AbbSum1032, AbbSum268, AbbSum556, AbbSum251
	common /gzabbrev/ AbbSum1022, AbbSum389, AbbSum376, AbbSum313
	common /gzabbrev/ AbbSum1245, AbbSum591, AbbSum235, AbbSum1126
	common /gzabbrev/ AbbSum297, AbbSum300, AbbSum403, AbbSum416
	common /gzabbrev/ AbbSum250, AbbSum1021, AbbSum557, AbbSum580
	common /gzabbrev/ AbbSum1149, AbbSum525, AbbSum635, AbbSum349
	common /gzabbrev/ AbbSum294, AbbSum362, AbbSum248, AbbSum269
	common /gzabbrev/ AbbSum278, AbbSum262, AbbSum438, AbbSum321
	common /gzabbrev/ AbbSum459, AbbSum1114, AbbSum382, AbbSum1256
	common /gzabbrev/ AbbSum295, AbbSum279, AbbSum414, AbbSum410
	common /gzabbrev/ AbbSum247, AbbSum420, AbbSum232, AbbSum424
	common /gzabbrev/ AbbSum1154, AbbSum560, AbbSum224, AbbSum588
	common /gzabbrev/ AbbSum430, AbbSum428, AbbSum1044, AbbSum1042
	common /gzabbrev/ AbbSum491, AbbSum641, AbbSum361, AbbSum293
	common /gzabbrev/ AbbSum242, AbbSum350, AbbSum1148, AbbSum644
	common /gzabbrev/ AbbSum1295, AbbSum839, AbbSum1168
	common /gzabbrev/ AbbSum1173, AbbSum964, AbbSum734, AbbSum1229
	common /gzabbrev/ AbbSum819, AbbSum504, AbbSum474, AbbSum470
	common /gzabbrev/ AbbSum617, AbbSum938, AbbSum738, AbbSum1140
	common /gzabbrev/ AbbSum754, AbbSum1003, AbbSum995, AbbSum935
	common /gzabbrev/ AbbSum828, AbbSum732, AbbSum730, AbbSum1144
	common /gzabbrev/ AbbSum805, AbbSum815, AbbSum574, AbbSum288
	common /gzabbrev/ AbbSum305, AbbSum298, AbbSum628, AbbSum615
	common /gzabbrev/ AbbSum788, AbbSum769, AbbSum792, AbbSum495
	common /gzabbrev/ AbbSum661, AbbSum653, AbbSum455, AbbSum937
	common /gzabbrev/ AbbSum913, AbbSum1230, AbbSum887, AbbSum865
	common /gzabbrev/ AbbSum697, AbbSum867, AbbSum1172, AbbSum1167
	common /gzabbrev/ AbbSum1266, AbbSum1296, AbbSum901, AbbSum980
	common /gzabbrev/ AbbSum625, AbbSum837, AbbSum835, AbbSum761
	common /gzabbrev/ AbbSum1171, AbbSum1069, AbbSum1300
	common /gzabbrev/ AbbSum1006, AbbSum1288, AbbSum743, AbbSum741
	common /gzabbrev/ AbbSum813, AbbSum811, AbbSum1176, AbbSum1165
	common /gzabbrev/ AbbSum749, AbbSum746, AbbSum465, AbbSum118
	common /gzabbrev/ AbbSum845, AbbSum861, AbbSum881, AbbSum943
	common /gzabbrev/ AbbSum1066, AbbSum857, AbbSum1242, AbbSum843
	common /gzabbrev/ AbbSum859, AbbSum1240, AbbSum849, AbbSum987
	common /gzabbrev/ AbbSum1158, AbbSum1280, AbbSum303, AbbSum779
	common /gzabbrev/ AbbSum974, AbbSum990, AbbSum549, AbbSum618
	common /gzabbrev/ AbbSum693, AbbSum947, AbbSum684, AbbSum914
	common /gzabbrev/ AbbSum594, AbbSum714, AbbSum206, AbbSum1018
	common /gzabbrev/ AbbSum770, AbbSum793, AbbSum1128, AbbSum668
	common /gzabbrev/ AbbSum1267, AbbSum678, AbbSum924, AbbSum956
	common /gzabbrev/ AbbSum561, AbbSum606, AbbSum299, AbbSum1013
	common /gzabbrev/ AbbSum314, AbbSum1004, AbbSum996, AbbSum1198
	common /gzabbrev/ AbbSum1246, AbbSum302, AbbSum404, AbbSum1014
	common /gzabbrev/ AbbSum1141, AbbSum616, AbbSum936, AbbSum1145
	common /gzabbrev/ AbbSum704, AbbSum707, AbbSum72, AbbSum663
	common /gzabbrev/ AbbSum709, AbbSum739, AbbSum731, AbbSum755
	common /gzabbrev/ AbbSum806, AbbSum733, AbbSum789, AbbSum829
	common /gzabbrev/ AbbSum562, AbbSum607, AbbSum955, AbbSum925
	common /gzabbrev/ AbbSum679, AbbSum377, AbbSum1127, AbbSum669
	common /gzabbrev/ AbbSum713, AbbSum205, AbbSum289, AbbSum1017
	common /gzabbrev/ AbbSum575, AbbSum948, AbbSum595, AbbSum683
	common /gzabbrev/ AbbSum735, AbbSum390, AbbSum1223, AbbSum692
	common /gzabbrev/ AbbSum335, AbbSum1261, AbbSum1211, AbbSum728
	common /gzabbrev/ AbbSum387, AbbSum782, AbbSum1002, AbbSum386
	common /gzabbrev/ AbbSum328, AbbSum356, AbbSum284, AbbSum276
	common /gzabbrev/ AbbSum388, AbbSum285, AbbSum1028, AbbSum355
	common /gzabbrev/ AbbSum348, AbbSum287, AbbSum1085, AbbSum218
	common /gzabbrev/ AbbSum214, AbbSum1079, AbbSum1089
	common /gzabbrev/ AbbSum1077, AbbSum1226, AbbSum1228
	common /gzabbrev/ AbbSum435, AbbSum1217, AbbSum1058
	common /gzabbrev/ AbbSum1104, AbbSum1178, AbbSum482, AbbSum532
	common /gzabbrev/ AbbSum344, AbbSum1115, AbbSum1124, AbbSum554
	common /gzabbrev/ AbbSum1278, AbbSum1281, AbbSum1159
	common /gzabbrev/ AbbSum727, AbbSum729, AbbSum783, AbbSum765
	common /gzabbrev/ AbbSum879, AbbSum885, AbbSum1276, AbbSum781
	common /gzabbrev/ AbbSum691, AbbSum917, AbbSum604, AbbSum954
	common /gzabbrev/ AbbSum614, AbbSum573, AbbSum666, AbbSum1139
	common /gzabbrev/ AbbSum712, AbbSum720, AbbSum674, AbbSum31
	common /gzabbrev/ AbbSum201, AbbSum33, AbbSum875, AbbSum28
	common /gzabbrev/ AbbSum29, AbbSum1060, AbbSum963, AbbSum934
	common /gzabbrev/ AbbSum907, AbbSum487, AbbSum500, AbbSum660
	common /gzabbrev/ AbbSum1294, AbbSum1030, AbbSum1262
	common /gzabbrev/ AbbSum1097, AbbSum965, AbbSum526, AbbSum636
	common /gzabbrev/ AbbSum902, AbbSum981, AbbSum507, AbbSum970
	common /gzabbrev/ AbbSum323, AbbSum622, AbbSum365, AbbSum975
	common /gzabbrev/ AbbSum156, AbbSum630, AbbSum266, AbbSum439
	common /gzabbrev/ AbbSum850, AbbSum722, AbbSum752, AbbSum1068
	common /gzabbrev/ AbbSum972, AbbSum398, AbbSum801, AbbSum273
	common /gzabbrev/ AbbSum55, AbbSum104, AbbSum846, AbbSum437
	common /gzabbrev/ AbbSum603, AbbSum271, AbbSum185, AbbSum476
	common /gzabbrev/ AbbSum510, AbbSum1191, AbbSum441, AbbSum440
	common /gzabbrev/ AbbSum853, AbbSum1213, AbbSum877, AbbSum181
	common /gzabbrev/ AbbSum434, AbbSum851, AbbSum442, AbbSum847
	common /gzabbrev/ AbbSum991, AbbSum645, AbbSum490, AbbSum503
	common /gzabbrev/ AbbSum992, AbbSum962, AbbSum514, AbbSum640
	common /gzabbrev/ AbbSum508, AbbSum497, AbbSum623, AbbSum506
	common /gzabbrev/ AbbSum973, AbbSum889, AbbSum646, AbbSum399
	common /gzabbrev/ AbbSum723, AbbSum725, AbbSum602, AbbSum551
	common /gzabbrev/ AbbSum612, AbbSum530, AbbSum601, AbbSum324
	common /gzabbrev/ AbbSum648, AbbSum458, AbbSum77, AbbSum478
	common /gzabbrev/ AbbSum613, AbbSum341, AbbSum986, AbbSum473
	common /gzabbrev/ AbbSum893, AbbSum624, AbbSum971, AbbSum833
	common /gzabbrev/ AbbSum370, AbbSum906, AbbSum467, AbbSum953
	common /gzabbrev/ AbbSum961, AbbSum816, AbbSum976, AbbSum417
	common /gzabbrev/ AbbSum1186, AbbSum1012, AbbSum227, AbbSum183
	common /gzabbrev/ AbbSum484, AbbSum1093, AbbSum446, AbbSum753
	common /gzabbrev/ AbbSum1286, AbbSum1156, AbbSum662, AbbSum667
	common /gzabbrev/ AbbSum520, AbbSum157, AbbSum159, AbbSum418
	common /gzabbrev/ AbbSum898, AbbSum1187, AbbSum432, AbbSum427
	common /gzabbrev/ AbbSum869, AbbSum587, AbbSum817, AbbSum632
	common /gzabbrev/ AbbSum852, AbbSum868, AbbSum105, AbbSum908
	common /gzabbrev/ AbbSum905, AbbSum862, AbbSum984, AbbSum1208
	common /gzabbrev/ AbbSum1283, AbbSum873, AbbSum79, AbbSum1166
	common /gzabbrev/ AbbSum876, AbbSum97, AbbSum92, AbbSum180
	common /gzabbrev/ AbbSum724, AbbSum1155, AbbSum874, AbbSum61
	common /gzabbrev/ AbbSum918, AbbSum463, AbbSum452, AbbSum600
	common /gzabbrev/ AbbSum99, AbbSum968, AbbSum608, AbbSum486
	common /gzabbrev/ AbbSum619, AbbSum391, AbbSum621, AbbSum1125
	common /gzabbrev/ AbbSum555, AbbSum512, AbbSum969, AbbSum960
	common /gzabbrev/ AbbSum496, AbbSum658, AbbSum1263, AbbSum951
	common /gzabbrev/ AbbSum489, AbbSum502, AbbSum499, AbbSum685
	common /gzabbrev/ AbbSum480, AbbSum1264, AbbSum597, AbbSum966
	common /gzabbrev/ AbbSum620, AbbSum609, AbbSum598, AbbSum605
	common /gzabbrev/ AbbSum599, AbbSum639, AbbSum529, AbbSum493
	common /gzabbrev/ AbbSum638, AbbSum528, AbbSum533, AbbSum949
	common /gzabbrev/ AbbSum270, AbbSum392, AbbSum73, AbbSum337
	common /gzabbrev/ AbbSum665, AbbSum959, AbbSum626, AbbSum610
	common /gzabbrev/ AbbSum454, AbbSum74, AbbSum95, AbbSum637
	common /gzabbrev/ AbbSum505, AbbSum888, AbbSum548, AbbSum527
	common /gzabbrev/ AbbSum477, AbbSum982, AbbSum903, AbbSum494
	common /gzabbrev/ AbbSum882, AbbSum103, AbbSum596, AbbSum481
	common /gzabbrev/ AbbSum184, AbbSum950, AbbSum100, AbbSum883
	common /gzabbrev/ AbbSum967, AbbSum958, AbbSum98, AbbSum93
	common /gzabbrev/ AbbSum796, AbbSum611, AbbSum830, AbbSum466
	common /gzabbrev/ AbbSum589, AbbSum457, AbbSum472, AbbSum469
	common /gzabbrev/ AbbSum96, AbbSum892, AbbSum519, AbbSum957
	common /gzabbrev/ AbbSum784, AbbSum642, AbbSum475, AbbSum509
	common /gzabbrev/ AbbSum395, AbbSum1010, AbbSum223, AbbSum431
	common /gzabbrev/ AbbSum451, AbbSum1024, AbbSum721, AbbSum1025
	common /gzabbrev/ AbbSum352, AbbSum1026, AbbSum243, AbbSum1007
	common /gzabbrev/ AbbSum1027, AbbSum353, AbbSum272, AbbSum158
	common /gzabbrev/ AbbSum785, AbbSum267, AbbSum791, AbbSum396
	common /gzabbrev/ AbbSum1016, AbbSum86, AbbSum56, AbbSum94
	common /gzabbrev/ AbbSum1015, AbbSum422, AbbSum1011, AbbSum426
	common /gzabbrev/ AbbSum231, AbbSum245, AbbSum423, AbbSum690
	common /gzabbrev/ AbbSum102, AbbSum1190, AbbSum182, AbbSum863
	common /gzabbrev/ AbbSum904, AbbSum62, AbbSum983, AbbSum101
	common /gzabbrev/ AbbSum483, AbbSum107, AbbSum1092, AbbSum445
	common /gzabbrev/ AbbSum464, AbbSum106, AbbSum585, AbbSum988
	common /gzabbrev/ AbbSum790, AbbSum897, AbbSum281, AbbSum372
	common /gzabbrev/ AbbSum249, AbbSum237, AbbSum280, AbbSum368
	common /gzabbrev/ AbbSum246, AbbSum236, AbbSum400, AbbSum1147
	common /gzabbrev/ AbbSum747, AbbSum825, AbbSum1238, AbbSum1000
	common /gzabbrev/ AbbSum923, AbbSum291, AbbSum577, AbbSum397
	common /gzabbrev/ AbbSum1146, AbbSum745, AbbSum823, AbbSum1235
	common /gzabbrev/ AbbSum999, AbbSum922, AbbSum290, AbbSum576
	common /gzabbrev/ AbbSum360, AbbSum277, AbbSum195, AbbSum216
	common /gzabbrev/ AbbSum204, AbbSum803, AbbSum737, AbbSum933
	common /gzabbrev/ AbbSum998, AbbSum1020, AbbSum681, AbbSum208
	common /gzabbrev/ AbbSum706, AbbSum193, AbbSum1143, AbbSum1138
	common /gzabbrev/ AbbSum572, AbbSum449, AbbSum460, AbbSum443
	common /gzabbrev/ AbbSum870, AbbSum34, AbbSum871, AbbSum444
	common /gzabbrev/ AbbSum461, AbbSum450, AbbSum32, AbbSum359
	common /gzabbrev/ AbbSum275, AbbSum194, AbbSum213, AbbSum200
	common /gzabbrev/ AbbSum799, AbbSum736, AbbSum930, AbbSum997
	common /gzabbrev/ AbbSum1019, AbbSum680, AbbSum207, AbbSum705
	common /gzabbrev/ AbbSum192, AbbSum1142, AbbSum1135, AbbSum568
	common /gzabbrev/ AbbSum75, AbbSum71, AbbSum76, AbbSum91
	common /gzabbrev/ AbbSum1257, AbbSum1289, AbbSum447, AbbSum629
	common /gzabbrev/ AbbSum1251, AbbSum854, AbbSum132, AbbSum521
	common /gzabbrev/ AbbSum540, AbbSum826, AbbSum633, AbbSum345
	common /gzabbrev/ AbbSum522, AbbSum776, AbbSum411, AbbSum383
	common /gzabbrev/ AbbSum890, AbbSum513, AbbSum985, AbbSum339
	common /gzabbrev/ AbbSum899, AbbSum977, AbbSum774, AbbSum946
	common /gzabbrev/ AbbSum1132, AbbSum809, AbbSum1113
	common /gzabbrev/ AbbSum1259, AbbSum1290, AbbSum686, AbbSum331
	common /gzabbrev/ AbbSum687, AbbSum448, AbbSum787, AbbSum1121
	common /gzabbrev/ AbbSum1112, AbbSum1102, AbbSum891, AbbSum631
	common /gzabbrev/ AbbSum592, AbbSum552, AbbSum579, AbbSum945
	common /gzabbrev/ AbbSum307, AbbSum1110, AbbSum380, AbbSum855
	common /gzabbrev/ AbbSum1101, AbbSum1122, AbbSum1119
	common /gzabbrev/ AbbSum1120, AbbSum688, AbbSum1163, AbbSum134
	common /gzabbrev/ AbbSum827, AbbSum1204, AbbSum154, AbbSum689
	common /gzabbrev/ AbbSum952, AbbSum1197, AbbSum634, AbbSum511
	common /gzabbrev/ AbbSum538, AbbSum515, AbbSum1133, AbbSum1272
	common /gzabbrev/ AbbSum347, AbbSum578, AbbSum524, AbbSum1285
	common /gzabbrev/ AbbSum778, AbbSum786, AbbSum537, AbbSum531
	common /gzabbrev/ AbbSum768, AbbSum253, AbbSum413, AbbSum804
	common /gzabbrev/ AbbSum539, AbbSum177, AbbSum912, AbbSum393
	common /gzabbrev/ AbbSum333, AbbSum523, AbbSum385, AbbSum401
	common /gzabbrev/ AbbSum373, AbbSum329, AbbSum311, AbbSum375
	common /gzabbrev/ AbbSum160, AbbSum1244, AbbSum541, AbbSum1265
	common /gzabbrev/ AbbSum553, AbbSum542, AbbSum979, AbbSum543
	common /gzabbrev/ AbbSum944, AbbSum1094, AbbSum516, AbbSum1192
	common /gzabbrev/ AbbSum176, AbbSum312, AbbSum153, AbbSum1210
	common /gzabbrev/ AbbSum593, AbbSum894, AbbSum1108, AbbSum534
	common /gzabbrev/ AbbSum252, AbbSum374, AbbSum1243, AbbSum1095
	common /gzabbrev/ AbbSum909, AbbSum1252, AbbSum1157
	common /gzabbrev/ AbbSum1279, AbbSum402, AbbSum900, AbbSum394
	common /gzabbrev/ AbbSum978, AbbSum1109, AbbSum1090, AbbSum535
	common /gzabbrev/ AbbSum929, AbbSum1258, AbbSum1200, AbbSum330
	common /gzabbrev/ AbbSum1254, AbbSum654, AbbSum1292, AbbSum186
	common /gzabbrev/ AbbSum363, AbbSum1188, AbbSum910, AbbSum1130
	common /gzabbrev/ AbbSum306, AbbSum320, AbbSum197, AbbSum1162
	common /gzabbrev/ AbbSum161, AbbSum1195, AbbSum915, AbbSum1234
	common /gzabbrev/ AbbSum766, AbbSum178, AbbSum241, AbbSum795
	common /gzabbrev/ AbbSum220, AbbSum221, AbbSum993, AbbSum696
	common /gzabbrev/ AbbSum115, AbbSum128, AbbSum126, AbbSum108
	common /gzabbrev/ AbbSum124, AbbSum1206, AbbSum1231, AbbSum130
	common /gzabbrev/ AbbSum120, AbbSum122, AbbSum1070, AbbSum1169
	common /gzabbrev/ AbbSum1174, AbbSum1233, AbbSum255, AbbSum165
	common /gzabbrev/ AbbSum163, AbbSum821, AbbSum840, AbbSum1072
	common /gzabbrev/ AbbSum1087, AbbSum820, AbbSum717, AbbSum325
	common /gzabbrev/ AbbSum649, AbbSum316, AbbSum1008, AbbSum517
	common /gzabbrev/ AbbSum700, AbbSum701, AbbSum229, AbbSum1106
	common /gzabbrev/ AbbSum230, AbbSum309, AbbSum364, AbbSum167
	common /gzabbrev/ AbbSum797, AbbSum794, AbbSum558, AbbSum1150
	common /gzabbrev/ AbbSum1131, AbbSum582, AbbSum939, AbbSum1297
	common /gzabbrev/ AbbSum1207, AbbSum673, AbbSum772, AbbSum566
	common /gzabbrev/ AbbSum1083, AbbSum1247, AbbSum567, AbbSum940
	common /gzabbrev/ AbbSum927, AbbSum1151, AbbSum545, AbbSum1270
	common /gzabbrev/ AbbSum1221, AbbSum1220, AbbSum1269
	common /gzabbrev/ AbbSum564, AbbSum547, AbbSum926, AbbSum583
	common /gzabbrev/ AbbSum1129, AbbSum672, AbbSum1268, AbbSum407
	common /gzabbrev/ AbbSum210, AbbSum758, AbbSum136, AbbSum762
	common /gzabbrev/ AbbSum1036, AbbSum1046, AbbSum258, AbbSum895
	common /gzabbrev/ AbbSum357, AbbSum148, AbbSum146, AbbSum340
	common /gzabbrev/ AbbSum366, AbbSum695, AbbSum671, AbbSum133
	common /gzabbrev/ AbbSum750, AbbSum351, AbbSum144, AbbSum150
	common /gzabbrev/ AbbSum140, AbbSum257, AbbSum142, AbbSum1117
	common /gzabbrev/ AbbSum710, AbbSum1179, AbbSum1098, AbbSum563
	common /gzabbrev/ AbbSum1116, AbbSum1202, AbbSum1111
	common /gzabbrev/ AbbSum941, AbbSum916, AbbSum559, AbbSum1091
	common /gzabbrev/ AbbSum1232, AbbSum536, AbbSum1260
	common /gzabbrev/ AbbSum1201, AbbSum189, AbbSum655, AbbSum332
	common /gzabbrev/ AbbSum1298, AbbSum1293, AbbSum1255
	common /gzabbrev/ AbbSum798, AbbSum367, AbbSum1189, AbbSum911
	common /gzabbrev/ AbbSum162, AbbSum322, AbbSum202, AbbSum1137
	common /gzabbrev/ AbbSum1164, AbbSum308, AbbSum1209, AbbSum584
	common /gzabbrev/ AbbSum315, AbbSum336, AbbSum59, AbbSum60
	common /gzabbrev/ AbbSum1199, AbbSum767, AbbSum179, AbbSum1237
	common /gzabbrev/ AbbSum1105, AbbSum226, AbbSum225, AbbSum994
	common /gzabbrev/ AbbSum263, AbbSum1009, AbbSum310, AbbSum172
	common /gzabbrev/ AbbSum1153, AbbSum119, AbbSum164, AbbSum326
	common /gzabbrev/ AbbSum129, AbbSum127, AbbSum518, AbbSum699
	common /gzabbrev/ AbbSum166, AbbSum369, AbbSum802, AbbSum110
	common /gzabbrev/ AbbSum824, AbbSum650, AbbSum800, AbbSum318
	common /gzabbrev/ AbbSum702, AbbSum703, AbbSum233, AbbSum125
	common /gzabbrev/ AbbSum841, AbbSum1107, AbbSum234, AbbSum1212
	common /gzabbrev/ AbbSum1236, AbbSum131, AbbSum121, AbbSum586
	common /gzabbrev/ AbbSum123, AbbSum546, AbbSum1134, AbbSum405
	common /gzabbrev/ AbbSum378, AbbSum1181, AbbSum832, AbbSum1100
	common /gzabbrev/ AbbSum757, AbbSum1061, AbbSum57, AbbSum48
	common /gzabbrev/ AbbSum1057, AbbSum152, AbbSum82, AbbSum1075
	common /gzabbrev/ AbbSum659, AbbSum1056, AbbSum652, AbbSum80
	common /gzabbrev/ AbbSum81, AbbSum831, AbbSum756, AbbSum1160
	common /gzabbrev/ AbbSum1180, AbbSum1099, AbbSum807, AbbSum771
	common /gzabbrev/ AbbSum571, AbbSum677, AbbSum570, AbbSum775
	common /gzabbrev/ AbbSum1250, AbbSum358, AbbSum1161, AbbSum808
	common /gzabbrev/ AbbSum773, AbbSum942, AbbSum932, AbbSum1170
	common /gzabbrev/ AbbSum1152, AbbSum1175, AbbSum1224
	common /gzabbrev/ AbbSum1274, AbbSum1248, AbbSum550, AbbSum569
	common /gzabbrev/ AbbSum931, AbbSum822, AbbSum1271, AbbSum1282
	common /gzabbrev/ AbbSum256, AbbSum215, AbbSum408, AbbSum1222
	common /gzabbrev/ AbbSum759, AbbSum1136, AbbSum676, AbbSum1071
	common /gzabbrev/ AbbSum1273, AbbSum260, AbbSum1084
	common /gzabbrev/ AbbSum1073, AbbSum1088, AbbSum719, AbbSum716
	common /gzabbrev/ AbbSum718, AbbSum85, AbbSum83, AbbSum54
	common /gzabbrev/ AbbSum84, AbbSum1196, AbbSum138, AbbSum149
	common /gzabbrev/ AbbSum147, AbbSum342, AbbSum135, AbbSum354
	common /gzabbrev/ AbbSum145, AbbSum151, AbbSum141, AbbSum143
	common /gzabbrev/ AbbSum896, AbbSum763, AbbSum751, AbbSum698
	common /gzabbrev/ AbbSum1038, AbbSum371, AbbSum675, AbbSum1048
	common /gzabbrev/ AbbSum1194, AbbSum1062, AbbSum168, AbbSum58
	common /gzabbrev/ AbbSum1076, AbbSum1041, AbbSum155
	common /gzabbrev/ AbbSum1040, AbbSum222, AbbSum1182
	common /gzabbrev/ AbbSum1103, AbbSum244, AbbSum711, AbbSum379
	common /gzabbrev/ AbbSum406, AbbSum338, AbbSum317, AbbSum928
	common /gzabbrev/ AbbSum1123, AbbSum565, AbbSum1284
	common /gzabbrev/ AbbSum1203, AbbSum1118, AbbSum1249

	integer*8 iint1(3),iint2(3),iint3(3),iint4(3),iint5(3)
	integer*8 iint6(3),iint7(3),iint8(3),iint9(3),iint10(3)
	integer*8 iint11(3),iint12(3),iint13(3),iint14(3),iint15(3)
	integer*8 iint16(3),iint17(3),iint18(3),iint19(3),iint20(3)
	integer*8 iint21(3),iint22(3),iint23(3),iint24(3),iint25(3)
	integer*8 iint26(3),iint27(3),iint28(3),iint29(3),iint30(3)
	integer*8 iint31(3),iint32(3),iint33(3),iint34(3),iint35(3)
	integer*8 iint36(3),iint37(2),iint38(2),iint39(2),iint40(2)
	integer*8 iint41(2),iint42(2),iint43(2),iint44(2),iint45(2)
	integer*8 iint46(2),iint47(2),iint48(2),iint49(2),iint50(2)
	integer*8 iint51(2),iint52(2),iint53,iint54,iint55,iint56
	integer*8 iint57(3),iint58(3),iint59(3),iint60(3),iint61(3)
	integer*8 iint62(3),iint63(3),iint64(3),iint65(3),iint66(3)
	integer*8 iint67(3),iint68(3),iint69(2,2),iint70(2,2),iint71
	integer*8 iint72,iint73(3),iint74(3),iint75(3),iint76(3)
	integer*8 iint77(3),iint78(3),iint79(3),iint80(3),iint81(3)
	integer*8 iint82(3),iint83(3),iint84(3),iint85(3),iint86(3)
	integer*8 iint87(3),iint88(3),iint89(3),iint90(3),iint91(3)
	integer*8 iint92(3),iint93(3),iint94(3),iint95(3),iint96(3)
	integer*8 iint97(3),iint98(3),iint99(3),iint100(3)
	integer*8 iint101(3),iint102(3),iint103(3),iint104(3)
	integer*8 iint105(3),iint106(3),iint107(3),iint108(3)
	integer*8 iint109(3),iint110(3),iint111(3),iint112(3)
	integer*8 iint113(3),iint114(3),iint115(3),iint116(3)
	integer*8 iint117(3),iint118(3),iint119(3),iint120(3)
	integer*8 iint121(3),iint122(3),iint123(3),iint124(3)
	integer*8 iint125(3),iint126(3),iint127(3),iint128(3)
	integer*8 iint129(3),iint130(3),iint131(3),iint132(3)
	integer*8 iint133(3),iint134(3),iint135(3),iint136(3)
	integer*8 iint137(3),iint138(3),iint139(3),iint140(3)
	integer*8 iint141(3),iint142(3),iint143(3),iint144(3)
	integer*8 iint145(3),iint146(3),iint147(3),iint148(3)
	integer*8 iint149(3),iint150(3),iint151(3),iint152(3)
	integer*8 iint153(3),iint154(3),iint155(3),iint156(3)
	integer*8 iint157(3),iint158(3),iint159(3),iint160(3)
	integer*8 iint161(3),iint162(3),iint163(3),iint164(3)
	integer*8 iint165(3),iint166(3),iint167(3),iint168(3)
	integer*8 iint169(3),iint170(3),iint171(3),iint172(3)
	integer*8 iint173(3),iint174(3),iint175(2),iint176(2)
	integer*8 iint177(2),iint178(2),iint179(2),iint180(2)
	integer*8 iint181(2),iint182(2),iint183(2),iint184(2)
	integer*8 iint185,iint186,iint187(2),iint188(2),iint189(2)
	integer*8 iint190(2),iint191(2),iint192(2,2),iint193(2,2)
	integer*8 iint194(2,2),iint195(2,2),iint196(2,2),iint197(2,2)
	integer*8 iint198(2,2),iint199(2,2),iint200(2,2),iint201(2,2)
	integer*8 iint202(2,2),iint203(2,2),iint204(2,2)
	common /gzloopint/ iint1, iint2, iint3, iint4, iint5, iint6
	common /gzloopint/ iint7, iint8, iint9, iint10, iint11, iint12
	common /gzloopint/ iint13, iint14, iint15, iint16, iint17
	common /gzloopint/ iint18, iint19, iint20, iint21, iint22
	common /gzloopint/ iint23, iint24, iint25, iint26, iint27
	common /gzloopint/ iint28, iint29, iint30, iint31, iint32
	common /gzloopint/ iint33, iint34, iint35, iint36, iint37
	common /gzloopint/ iint38, iint39, iint40, iint41, iint42
	common /gzloopint/ iint43, iint44, iint45, iint46, iint47
	common /gzloopint/ iint48, iint49, iint50, iint51, iint52
	common /gzloopint/ iint53, iint54, iint55, iint56, iint57
	common /gzloopint/ iint58, iint59, iint60, iint61, iint62
	common /gzloopint/ iint63, iint64, iint65, iint66, iint67
	common /gzloopint/ iint68, iint69, iint70, iint71, iint72
	common /gzloopint/ iint73, iint74, iint75, iint76, iint77
	common /gzloopint/ iint78, iint79, iint80, iint81, iint82
	common /gzloopint/ iint83, iint84, iint85, iint86, iint87
	common /gzloopint/ iint88, iint89, iint90, iint91, iint92
	common /gzloopint/ iint93, iint94, iint95, iint96, iint97
	common /gzloopint/ iint98, iint99, iint100, iint101, iint102
	common /gzloopint/ iint103, iint104, iint105, iint106, iint107
	common /gzloopint/ iint108, iint109, iint110, iint111, iint112
	common /gzloopint/ iint113, iint114, iint115, iint116, iint117
	common /gzloopint/ iint118, iint119, iint120, iint121, iint122
	common /gzloopint/ iint123, iint124, iint125, iint126, iint127
	common /gzloopint/ iint128, iint129, iint130, iint131, iint132
	common /gzloopint/ iint133, iint134, iint135, iint136, iint137
	common /gzloopint/ iint138, iint139, iint140, iint141, iint142
	common /gzloopint/ iint143, iint144, iint145, iint146, iint147
	common /gzloopint/ iint148, iint149, iint150, iint151, iint152
	common /gzloopint/ iint153, iint154, iint155, iint156, iint157
	common /gzloopint/ iint158, iint159, iint160, iint161, iint162
	common /gzloopint/ iint163, iint164, iint165, iint166, iint167
	common /gzloopint/ iint168, iint169, iint170, iint171, iint172
	common /gzloopint/ iint173, iint174, iint175, iint176, iint177
	common /gzloopint/ iint178, iint179, iint180, iint181, iint182
	common /gzloopint/ iint183, iint184, iint185, iint186, iint187
	common /gzloopint/ iint188, iint189, iint190, iint191, iint192
	common /gzloopint/ iint193, iint194, iint195, iint196, iint197
	common /gzloopint/ iint198, iint199, iint200, iint201, iint202
	common /gzloopint/ iint203, iint204

	integer cha5, cha6, hia5, his5, ij, lpd5, neu5, qud5, quu5
	integer sld5, sle5, sqd5, sqe5, squ5, sqv5
	common /gzindices/ cha5, cha6, hia5, his5, ij, lpd5, neu5
	common /gzindices/ qud5, quu5, sld5, sle5, sqd5, sqe5, squ5
	common /gzindices/ sqv5

	double complex Cloop(1)
	common /gzformfactors/ Cloop

