cteq2pdt:
	cc -o ../pdTables/cteq2pdt cteq2pdt.c alpha.c -lm 

mrst2pdt:
	cc -o ../pdTables/mrst2pdt mrst2pdt.c alpha.c -lm
checkpdt:
	cc -o ../pdTables/checkpdt checkpdt.c ../c_source/num/pdt.c \
-I ../c_source/num/include -lm